import { SourceCitation, SOURCES } from './sourceRegistry';

export interface ChapterRuleMapping {
  chapterNumber: string;
  chapterTitleHi: string;
  chapterTitleEn: string;
  primaryPillar: 'CORE' | 'CAREER' | 'RELATIONSHIPS' | 'VASTU' | 'ACTION';
  calculatedInputs: string[];
  governingRuleIds: string[];
  sourceCitations: SourceCitation[];
  interpretationLevel: 'CALCULATED' | 'INTERPRETED' | 'RECOMMENDED';
  deterministicCaution: boolean;
  version: string;
  status: 'ACTIVE' | 'DOCUMENTED' | 'REVIEW_REQUIRED';
}

/**
 * Canonical 32-Chapter to Methodology Rule Governance Mapping Matrix
 * Ensures every single chapter has a traceable, non-contradictory mathematical and rule basis.
 */
export const CHAPTER_RULE_GOVERNANCE_MAP: Record<string, ChapterRuleMapping> = {
  '01': {
    chapterNumber: '01',
    chapterTitleHi: 'कार्यकारी सारांश एवं मुख्य प्रोफाइल',
    chapterTitleEn: 'Executive Summary & Core Snapshot',
    primaryPillar: 'CORE',
    calculatedInputs: ['DOB', 'Name', 'Mobile', 'Gender'],
    governingRuleIds: ['RULE_CORE_SYNTHESIS', 'RULE_CROSS_PATTERN_MATRIX', 'RULE_SNAPSHOT_AGGREGATE'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '02': {
    chapterNumber: '02',
    chapterTitleHi: 'मूलांक, भाग्यांक व आत्म-चेतना समन्वय',
    chapterTitleEn: 'Core Numbers & Synthesis (Driver & Conductor)',
    primaryPillar: 'CORE',
    calculatedInputs: ['Birth Day (1-31)', 'Full DOB Sum'],
    governingRuleIds: ['RULE_MULANK_CALCULATION', 'RULE_BHAGYANK_CALCULATION', 'RULE_PLANET_GRAHA_MAPPING'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.INDIAN_CLASSICAL_VEDIC],
    interpretationLevel: 'CALCULATED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '03': {
    chapterNumber: '03',
    chapterTitleHi: '3x3 लो शू जन्म कुंडली ग्रिड',
    chapterTitleEn: 'Natal 3x3 Lo Shu Birth Grid',
    primaryPillar: 'CORE',
    calculatedInputs: ['DOB Digits'],
    governingRuleIds: ['RULE_LOSHU_BIRTH_GRID_POPULATION', 'RULE_3X3_COSMIC_SECTOR_ALIGNMENT'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'CALCULATED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '04': {
    chapterNumber: '04',
    chapterTitleHi: '3-स्तरीय संश्लेषित ग्रिड विश्लेषण',
    chapterTitleEn: 'Enhanced 3-Layer Lo Shu Matrix',
    primaryPillar: 'CORE',
    calculatedInputs: ['DOB Digits', 'Mulank', 'Bhagyank'],
    governingRuleIds: ['RULE_ENHANCED_LOSHU_3_LAYER', 'RULE_FLAT_GRID_SYNTHESIS'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '05': {
    chapterNumber: '05',
    chapterTitleHi: 'सक्रिय एवं उपस्थित अंक आवृत्तियां',
    chapterTitleEn: 'Active & Present Number Frequencies',
    primaryPillar: 'CORE',
    calculatedInputs: ['Present Grid Digits'],
    governingRuleIds: ['RULE_PRESENT_NUMBER_TALENTS', 'RULE_ELEMENTAL_BALANCE_1_9'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '06': {
    chapterNumber: '06',
    chapterTitleHi: 'रिक्त अंक एवं कार्मिक पाठ',
    chapterTitleEn: 'Missing Numbers & Karmic Lessons',
    primaryPillar: 'CORE',
    calculatedInputs: ['Missing Grid Digits (0 to 9)'],
    governingRuleIds: ['RULE_MISSING_NUMBER_KARMIC_LESSON', 'RULE_ELEMENTAL_DEFICIT_MAPPING'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '07': {
    chapterNumber: '07',
    chapterTitleHi: 'अंकों की पुनरावृत्ति एवं अति-ऊर्जा प्रभाव',
    chapterTitleEn: 'Number Repetition & Over-Energy Analysis',
    primaryPillar: 'CORE',
    calculatedInputs: ['Digit Frequency Counts (1x, 2x, 3x, 4x+)'],
    governingRuleIds: ['RULE_NUMBER_REPETITION_INTENSITY', 'RULE_OVER_ENERGY_GROUNDING'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '08': {
    chapterNumber: '08',
    chapterTitleHi: '8 सफलता, मानसिक एवं व्यावहारिक तल',
    chapterTitleEn: '8 Success & Balance Planes',
    primaryPillar: 'CORE',
    calculatedInputs: ['Grid Rows, Columns & Diagonals'],
    governingRuleIds: ['RULE_8_LOSHU_PLANES_STRENGTH', 'RULE_PROSPERITY_PLANE_4_5_6', 'RULE_WILL_PLANE_9_5_1'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '09': {
    chapterNumber: '09',
    chapterTitleHi: 'पाइथागोरस एवं कार्मिक योग तीर',
    chapterTitleEn: 'Arrows of Pythagoras & Strength',
    primaryPillar: 'CORE',
    calculatedInputs: ['Complete 3-Digit Grid Lines'],
    governingRuleIds: ['RULE_12_ARROWS_STRENGTH_WEAKNESS', 'RULE_ARROW_DETERMINATION'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.PYTHAGOREAN_WESTERN],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '10': {
    chapterNumber: '10',
    chapterTitleHi: '81 वैदिक ग्रहीय युति एवं फल',
    chapterTitleEn: '81 Vedic Planetary Yogas',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Mulank (1-9)', 'Bhagyank (1-9)'],
    governingRuleIds: ['RULE_81_PLANETARY_YOGA_MATRIX', 'RULE_GRAH_DRISHTI_SYNERGY'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.INDIAN_CLASSICAL_VEDIC],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '11': {
    chapterNumber: '11',
    chapterTitleHi: 'मुख्य व्यक्तित्व प्रारूप एवं प्रारब्ध',
    chapterTitleEn: 'Primary Archetype & Karmic Blueprint',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Mulank', 'Bhagyank', 'Lo Shu Planes'],
    governingRuleIds: ['RULE_DOMINANT_ARCHETYPE', 'RULE_COSMIC_SIGNATURE'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '12': {
    chapterNumber: '12',
    chapterTitleHi: 'जीवन दिशा, भाग्यांक एवं आत्म अभिलाषा',
    chapterTitleEn: 'Life Destiny & Soul Urge Coordinates',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Bhagyank', 'Name Vowels / Pythagorean Vowel Sum'],
    governingRuleIds: ['RULE_SOUL_URGE_DESTINY_ALIGNMENT'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.PYTHAGOREAN_WESTERN],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '13': {
    chapterNumber: '13',
    chapterTitleHi: 'मानसिक, भावनात्मक एवं व्यावहारिक सोच',
    chapterTitleEn: 'Psychological & Cognitive Dynamics',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Row 1 (4-9-2)', 'Row 2 (3-5-7)', 'Row 3 (8-1-6)'],
    governingRuleIds: ['RULE_PSYCHOLOGICAL_COGNITIVE_PROFILING'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '14': {
    chapterNumber: '14',
    chapterTitleHi: 'करियर, आजीविका व अनुकूल व्यवसाय',
    chapterTitleEn: 'Career Aptitude & Professional Alignment',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Bhagyank', 'Dominant Plane', 'Active Digits'],
    governingRuleIds: ['RULE_CAREER_PROFESSION_MAPPING', 'RULE_ENTREPRENEURIAL_FIT'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.LEOFAMILY_CORE],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '15': {
    chapterNumber: '15',
    chapterTitleHi: 'धन, वित्तीय समृद्धि एवं जोखिम प्रबंधन',
    chapterTitleEn: 'Wealth, Finance & Abundance Blueprint',
    primaryPillar: 'CAREER',
    calculatedInputs: ['Plane 4-5-6', 'Dig 5 Presence', 'Dig 6 Presence', 'Dig 8 Presence'],
    governingRuleIds: ['RULE_WEALTH_ACCUMULATION_STYLE', 'RULE_FINANCIAL_CAUTION_DISCIPLINE'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '16': {
    chapterNumber: '16',
    chapterTitleHi: 'प्रेम, दांपत्य एवं संबंध अनुकूलता',
    chapterTitleEn: 'Love, Marriage & Relationship Approach',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['Mulank', 'Dig 2 Count', 'Dig 6 Count'],
    governingRuleIds: ['RULE_RELATIONSHIP_FAMILY_HARMONY', 'RULE_LOVE_LANGUAGE_COMMITMENT'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.INDIAN_CLASSICAL_VEDIC],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '17': {
    chapterNumber: '17',
    chapterTitleHi: 'सामाजिक प्रतिष्ठा एवं नेतृत्व क्षमता',
    chapterTitleEn: 'Social Image & Leadership Style',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['Dig 1 Count', 'Dig 9 Count', 'Mulank'],
    governingRuleIds: ['RULE_PUBLIC_IMAGE_LEADERSHIP'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '18': {
    chapterNumber: '18',
    chapterTitleHi: 'मोबाइल 10-अंकीय 81 जोड़ी गहन विश्लेषण',
    chapterTitleEn: 'Mobile 81-Pair Deep Matrix',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['10-digit Mobile', 'Zero transformation', '9 Adjacent Pairs'],
    governingRuleIds: [
      'RULE_MOBILE_PAIR_MATRIX_81',
      'RULE_MOBILE_ZERO_REPLACEMENT',
      'RULE_MOBILE_POSITIONAL_ROLES',
      'RULE_MOBILE_COMPOUND_CLASSIFICATION',
    ],
    sourceCitations: [
      SOURCES.LEOFAMILY_MOBILE_PDF_D1,
      SOURCES.LEOFAMILY_MOBILE_PDF_D2,
      SOURCES.LEOFAMILY_MOBILE_PDF_D3,
      SOURCES.LEOFAMILY_MOBILE_PDF_D4,
    ],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '19': {
    chapterNumber: '19',
    chapterTitleHi: 'चाल्डियन संयुक्त नामांक एवं स्पेलिंग कंपन',
    chapterTitleEn: 'Chaldean Compound Name Analysis',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['Full Name letters (Chaldean matrix 1-8)'],
    governingRuleIds: ['RULE_CHALDEAN_COMPOUND_DATABASE_10_52'],
    sourceCitations: [SOURCES.CHALDEAN_CHEYRO, SOURCES.LEOFAMILY_CORE],
    interpretationLevel: 'CALCULATED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '20': {
    chapterNumber: '20',
    chapterTitleHi: 'पाइथागोरियन नामांक एवं प्रकटीकरण',
    chapterTitleEn: 'Pythagorean Name Frequency & Expression',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['Full Name letters (Pythagorean 1-9 matrix)'],
    governingRuleIds: ['RULE_PYTHAGOREAN_EXPRESSION_REDUCTION'],
    sourceCitations: [SOURCES.PYTHAGOREAN_WESTERN],
    interpretationLevel: 'CALCULATED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '21': {
    chapterNumber: '21',
    chapterTitleHi: 'नाम स्पेलिंग शुद्धि एवं अक्षर संतुलन',
    chapterTitleEn: 'Name Spell Correction & Letter Tuning',
    primaryPillar: 'RELATIONSHIPS',
    calculatedInputs: ['Current Name Compound', 'Mulank / Bhagyank Harmony'],
    governingRuleIds: ['RULE_NAME_SPELL_BALANCING_METHODOLOGY'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.CHALDEAN_CHEYRO],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '22': {
    chapterNumber: '22',
    chapterTitleHi: 'न्यूमेरो वास्तु एवं 8-दिशा ऊर्जा संतुलन',
    chapterTitleEn: 'Numero Vastu & Directional Alignment',
    primaryPillar: 'VASTU',
    calculatedInputs: ['DOB Numbers', 'Missing Lo Shu Sectors'],
    governingRuleIds: ['RULE_NUMERO_VASTU_8_DIRECTIONS', 'RULE_RESIDENTIAL_ENERGY_FLOW'],
    sourceCitations: [SOURCES.LEOFAMILY_NUMERO_VASTU_PDF, SOURCES.LEOFAMILY_LOSHU_PDF],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '23': {
    chapterNumber: '23',
    chapterTitleHi: 'कुआ अंक एवं अष्ट दिशा शुभ-अशुभ चक्र',
    chapterTitleEn: 'Kua Number & 8 Mansions Compass Harmony',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Birth Year', 'Gender (MALE/FEMALE/OTHER)'],
    governingRuleIds: ['RULE_KUA_CALCULATION_GENDER_FORMULA', 'RULE_8_MANSIONS_DIRECTIONS'],
    sourceCitations: [SOURCES.LEOFAMILY_NUMERO_VASTU_PDF],
    interpretationLevel: 'CALCULATED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '24': {
    chapterNumber: '24',
    chapterTitleHi: 'आवास एवं कार्यस्थल ऊर्जा अभिविन्यास',
    chapterTitleEn: 'Residential & Workplace Spatial Energy',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Kua Sheng Chi', 'Kua Tian Yi', 'Kua Yan Nian'],
    governingRuleIds: ['RULE_WORKPLACE_RESIDENCE_ENTRANCE_ALIGNMENT'],
    sourceCitations: [SOURCES.LEOFAMILY_NUMERO_VASTU_PDF],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '25': {
    chapterNumber: '25',
    chapterTitleHi: 'व्यक्तिगत वर्ष चक्र एवं 3-वर्षीय कालखंड',
    chapterTitleEn: 'Personal Year Cyclic Vibration & 3-Year Forecast',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Birth Day', 'Birth Month', 'Target Calendar Year'],
    governingRuleIds: ['RULE_PERSONAL_YEAR_CYCLE_1_9', 'RULE_3_YEAR_FORECAST_TRANSITIONS'],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.INDIAN_CLASSICAL_VEDIC],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '26': {
    chapterNumber: '26',
    chapterTitleHi: 'वैदिक महादशा एवं अंतर्दशा समय चक्र',
    chapterTitleEn: 'Vedic Mahadasha & Antardasha Time Periods',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Mulank', 'DOB Year', 'Birthday Anniversary Date'],
    governingRuleIds: [
      'RULE_VEDIC_MAHADASHA_MULANK_SEQUENCE',
      'RULE_BIRTHDAY_ANNIVERSARY_DASHA_TRANSITION',
      'RULE_VEDIC_GRID_3X3_CALCULATION',
    ],
    sourceCitations: [
      SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D1_PDF,
      SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D2_PDF,
      SOURCES.INDIAN_CLASSICAL_VEDIC,
    ],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '27': {
    chapterNumber: '27',
    chapterTitleHi: 'ग्रहीय गोचर एवं अनुकूल समय चयन',
    chapterTitleEn: 'Planetary Transits & Auspicious Timing',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Day Lord', 'Personal Month', 'Personal Year'],
    governingRuleIds: ['RULE_MONTHLY_DASHA_YOG', 'RULE_DAY_LORD_MAPPING'],
    sourceCitations: [SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D2_PDF],
    interpretationLevel: 'INTERPRETED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '28': {
    chapterNumber: '28',
    chapterTitleHi: 'पारंपरिक आयुर्वेदिक स्वास्थ्य एवं त्रिदोष',
    chapterTitleEn: 'Traditional Ayurvedic & Astro-Wellness',
    primaryPillar: 'VASTU',
    calculatedInputs: ['Numbers 1-9 in DOB', 'Mulank Dosha Mapping'],
    governingRuleIds: ['RULE_AYURVEDIC_TRIDOSHA_PLANETARY_MAPPING', 'RULE_LIFESTYLE_DIETARY_ROUTINE'],
    sourceCitations: [
      SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D1_PDF,
      SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D2_PDF,
    ],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '29': {
    chapterNumber: '29',
    chapterTitleHi: 'हस्ताक्षर ऊर्जा एवं स्ट्रोक ऑडिट प्रो',
    chapterTitleEn: 'Signature Energy Audit Pro',
    primaryPillar: 'ACTION',
    calculatedInputs: ['Mulank', 'Bhagyank'],
    governingRuleIds: ['RULE_SIGNATURE_15_DEGREE_UPWARD', 'RULE_SIGNATURE_UNDERLINE_DISCIPLINE'],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.LEOFAMILY_CORE],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '30': {
    chapterNumber: '30',
    chapterTitleHi: 'वाहन, संपत्ति, बाल नामाक्षर व विवाह विस्तार',
    chapterTitleEn: 'Multi-Vehicle, Property & Synastry Extensions',
    primaryPillar: 'ACTION',
    calculatedInputs: ['Vehicle Number Sum', 'House Number Sum', 'Partner DOB', 'Child Initials'],
    governingRuleIds: [
      'RULE_VEHICLE_NUMEROLOGY_SYNERGY',
      'RULE_PROPERTY_FLAT_HARMONY',
      'RULE_SYNASTRY_COMPATIBILITY_SCORE',
      'RULE_CHILD_LUCKY_INITIALS',
    ],
    sourceCitations: [SOURCES.LEOFAMILY_CORE, SOURCES.INDIAN_CLASSICAL_VEDIC],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
  '31': {
    chapterNumber: '31',
    chapterTitleHi: 'प्रामाणिक वैदिक, मंत्र, यंत्र व लाल किताब उपाय',
    chapterTitleEn: 'Consolidated Vedic & Lal Kitab Remedies',
    primaryPillar: 'ACTION',
    calculatedInputs: ['Missing Digits', 'Mulank/Bhagyank Graha', 'Challenging Pairs'],
    governingRuleIds: [
      'RULE_YANTRA_PRIMARY_ASSIGNMENT',
      'RULE_MANTRA_SACRED_REPETITION_108',
      'RULE_COLOR_THERAPY_HARMONY',
      'RULE_CRYSTAL_GEMSTONE_DISCIPLINE',
      'RULE_PLANETARY_CHARITY_DISPENSATION',
    ],
    sourceCitations: [
      SOURCES.LEOFAMILY_LOSHU_PDF,
      SOURCES.LEOFAMILY_MEDICAL_NUMEROLOGY_D2_PDF,
      SOURCES.INDIAN_CLASSICAL_VEDIC,
    ],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: true,
    version: '1.0',
    status: 'ACTIVE',
  },
  '32': {
    chapterNumber: '32',
    chapterTitleHi: '90-दिवसीय व्यक्तिगत कार्य योजना एवं निष्कर्ष',
    chapterTitleEn: '90-Day Action Plan & Final Executive Guidance',
    primaryPillar: 'ACTION',
    calculatedInputs: ['All 31 Preceding Chapter Synthesis Results'],
    governingRuleIds: [
      'RULE_90_DAY_REMEDIAL_ALTAR_PROGRESSION',
      'RULE_EXECUTIVE_SUMMARY_7_TAKEAWAYS',
    ],
    sourceCitations: [SOURCES.LEOFAMILY_LOSHU_PDF, SOURCES.LEOFAMILY_CORE],
    interpretationLevel: 'RECOMMENDED',
    deterministicCaution: false,
    version: '1.0',
    status: 'ACTIVE',
  },
};
