export interface Combination81Entry {
  code: string;
  mulank: number;
  bhagyank: number;
  planetaryPair: string;
  title: string;
  positiveMeaning: string;
  negativeMeaning: string;
  careerMeaning: string;
  wealthMeaning: string;
  relationshipMeaning: string;
  spiritualMeaning: string;
  remedy: string;
  source: string;
}

export const COMBINATIONS_81_DATA: Record<string, Combination81Entry> = {
  // 1-SERIES (Sun Mulank)
  '1-1': {
    code: '1-1',
    mulank: 1,
    bhagyank: 1,
    planetaryPair: 'Sun - Sun',
    title: 'The Double Sun Sovereign (सूर्य-सूर्य एकाग्रता राजयोग)',
    positiveMeaning: 'Unshakeable authority, supreme confidence, independent executive vision, high moral standing, natural initiator, self-reliant.',
    negativeMeaning: 'Excessive ego clashes, authoritarian demeanor, impatience with slower teammates, occasional emotional isolation.',
    careerMeaning: 'Civil administration, senior politics, corporate CEO, pioneering technological inventions and startups.',
    wealthMeaning: 'Attracts high sovereign wealth, government contracts, independent income streams, avoid impulsive acquisitions.',
    relationshipMeaning: 'Fiercely protective but demands respect, personal space, and recognition from partner.',
    spiritualMeaning: 'Awakening of inner light, learning humility, righteous dharma, and solar plexus vitality.',
    remedy: 'Practice humility; offer water to rising sun (Surya Arghya) daily; drink from copper vessel; meditate on solar-plexus chakra.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-2': {
    code: '1-2',
    mulank: 1,
    bhagyank: 2,
    planetaryPair: 'Sun - Moon',
    title: 'The Sun-Moon King & Queen Union (सूर्य-चन्द्र राजयोग)',
    positiveMeaning: 'Harmonious synthesis of executive power and deep emotional empathy; magnetic charm, diplomacy, and balanced vision.',
    negativeMeaning: 'Inner conflict between firm authority and emotional sensitivity; occasional mood fluctuations or indecision.',
    careerMeaning: 'Public administration, diplomatic missions, media production, hospitality leadership, organizational counseling.',
    wealthMeaning: 'Steady, compounded prosperity; benefits from public goodwill, strategic partnerships, and liquid assets.',
    relationshipMeaning: 'Deeply romantic and devoted; balances domestic warmth with worldly stature and protective care.',
    spiritualMeaning: 'Union of Shiva and Shakti energies; balanced masculine leadership and feminine intuitive wisdom.',
    remedy: 'Drink water from a clean silver tumbler; respect and serve mother and father; wear light pastels on Mondays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-3': {
    code: '1-3',
    mulank: 1,
    bhagyank: 3,
    planetaryPair: 'Sun - Jupiter',
    title: 'Transformation Energy / Guru-Raja Yog (ज्ञान-सूर्य संगम)',
    positiveMeaning: 'Supreme intellectual brilliance, celestial guru-leader, scholarly authority, philosophical depth, broad advisory vision, and ethical optimism.',
    negativeMeaning: 'Overly didactic demeanor, tendency to lecture others, struggles to execute mundane administrative details, intellectual pride.',
    careerMeaning: 'Higher judiciary, university chancellorship, senior ministerial advisory, publishing, corporate coaching.',
    wealthMeaning: 'Immense prosperity through intellectual capital, ethical governance, advisory fees, and educational enterprises.',
    relationshipMeaning: 'Respectful, intellectually stimulating, and generous domestic environment; high mutual loyalty.',
    spiritualMeaning: 'Integration of sovereign power with Vedic spiritual guidelines and supreme wisdom (Brahma-Tejas).',
    remedy: 'Apply yellow saffron/haldi tilak on forehead/throat daily; honor spiritual teachers; support public libraries.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-4': {
    code: '1-4',
    mulank: 1,
    bhagyank: 4,
    planetaryPair: 'Sun - Rahu',
    title: 'The Electric Pioneer / Sun-Rahu Yog (सूर्य-राहु क्रांति योग)',
    positiveMeaning: 'Unconventional breakthrough thinking, sharp disruptive mind, sudden insights, technological disruption, high ambition, and global reach.',
    negativeMeaning: 'Sudden career fluctuations, legal hurdles, hidden enemies, risk of loans or defamation, bone/spine sensitivity.',
    careerMeaning: 'Information technology, space/aviation engineering, digital electronics, mass media, investigative journalism, politics.',
    wealthMeaning: 'Sudden unexpected windfalls alternating with sudden expenditures; requires prudent budgeting and avoidance of speculation.',
    relationshipMeaning: 'Complex dynamic; partner must understand unorthodox working rhythms and give breathing room.',
    spiritualMeaning: 'Piercing worldly illusions; transforming material obsession into penetrating spiritual insight.',
    remedy: 'Feed stray dogs on Saturdays; chant OM RAHAVE NAMAH; keep work desk clutter-free; avoid shady shortcuts.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-5': {
    code: '1-5',
    mulank: 1,
    bhagyank: 5,
    planetaryPair: 'Sun - Mercury',
    title: 'Attraction & Magnetism / Budhaditya Yog (सूर्य-बुध बुधादित्य)',
    positiveMeaning: 'Outstanding commercial intellect, Budhaditya Yoga, rapid calculation, high verbal expression, instant problem solving, persuasive eloquence.',
    negativeMeaning: 'Nervous speed, quick burnouts, restlessness, over-calculating which delays simple execution, critical of slow peers.',
    careerMeaning: 'International trade, strategic consulting, media broadcasting, tech venture entrepreneurship, finance brokerage, PR leadership.',
    wealthMeaning: 'High liquidity and rapid commercial compounding; multiplies capital quickly via retail or digital businesses.',
    relationshipMeaning: 'Vibrant, humorous, witty, and talkative companion; needs intellectual freedom and variety.',
    spiritualMeaning: 'Converts abstract philosophical knowledge into practical compassionate daily actions.',
    remedy: 'Keep a healthy green plant on desk; feed green grass to cows on Wednesdays; donate green lentils.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-6': {
    code: '1-6',
    mulank: 1,
    bhagyank: 6,
    planetaryPair: 'Sun - Venus',
    title: 'The Royal Splendor / Sun-Venus Yog (सूर्य-शुक्र वैभव योग)',
    positiveMeaning: 'Magnetic charisma, luxurious lifestyle, creative refinement, artistic aesthetic eye, commanding social presence.',
    negativeMeaning: 'Ego clashes in marriage, extravagant expenditures, money leakage, reproductive/lifestyle health strain.',
    careerMeaning: 'Luxury brand direction, film production, diplomatic hosting, haute couture, architecture, lifestyle hospitality.',
    wealthMeaning: 'Abundant luxury assets, premium vehicles, and high-net-worth social patronage; watch out for vanity spending.',
    relationshipMeaning: 'Passionate and lavish; needs mutual emotional validation, aesthetic harmony, and respectful communication.',
    spiritualMeaning: 'Recognizing divine beauty in the physical universe while transcending superficial vanity.',
    remedy: 'Donate white clothes or sweets to underprivileged girls on Fridays; wear sandalwood fragrance; practice dietary temperance.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-7': {
    code: '1-7',
    mulank: 1,
    bhagyank: 7,
    planetaryPair: 'Sun - Ketu',
    title: 'Fame & Recognition / Mystic Sovereign (सूर्य-केतु संधान तत्व योग)',
    positiveMeaning: 'Deep philosophical introspection, supernatural focus, analytical persistence, identifies hidden errors, quiet fame, government connections.',
    negativeMeaning: 'Feeling misunderstood, self-isolator, sudden spiritual detachments, distance from peers, indifference to worldly praise.',
    careerMeaning: 'Scientific research, deep forensics, astrology/occult studies, surgical leadership, patent engineering, deep software architecture.',
    wealthMeaning: 'Wealth comes through unique specialized mastery, intellectual properties, and confidential advisory assignments.',
    relationshipMeaning: 'Companion comfortable with quiet hours; values emotional authenticity and personal space over superficial gatherings.',
    spiritualMeaning: 'Moksha-oriented soul seeking self-realization beyond mundane accolades and titles.',
    remedy: 'Worship Lord Ganesha; support homeless shelters or donate woolen clothes to those in need on Saturdays; practice silent dhyana.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-8': {
    code: '1-8',
    mulank: 1,
    bhagyank: 8,
    planetaryPair: 'Sun - Saturn',
    title: 'Karmic Crucible / Sun-Saturn Yog (सूर्य-शनि कर्मयोग संघर्ष)',
    positiveMeaning: 'Monumental resilience, enduring work ethic, unshakeable discipline, profound patience, and ultimate triumph through perseverance.',
    negativeMeaning: 'Delayed early success, severe struggle in youth, friction with father figures or superiors, bone/joint stiffness.',
    careerMeaning: 'Heavy industry, corporate governance, civil construction, judiciary, public administration, mining, infrastructure.',
    wealthMeaning: 'Compounded permanent wealth built through decades of relentless effort; low bankruptcy risk, durable land holdings.',
    relationshipMeaning: 'Serious, responsible, and dedicated; may struggle to express lighthearted romance, requires patient partner.',
    spiritualMeaning: 'Burning of heavy ancestral karma through selfless duty, humility, and steadfast service.',
    remedy: 'Serve laborers and elderly workers on Saturdays; avoid arrogance; light mustard oil lamp under Peepal tree.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '1-9': {
    code: '1-9',
    mulank: 1,
    bhagyank: 9,
    planetaryPair: 'Sun - Mars',
    title: 'The Commander-in-Chief / Sun-Mars Yog (सूर्य-मंगल शौर्य योग)',
    positiveMeaning: 'Fearless bravery, explosive vitality, high-octane leadership, rapid execution, administrative dignity, and passionate humanitarian drive.',
    negativeMeaning: 'High temper, confrontational responses, impatience with hesitation, vulnerability to physical burnout or accidents.',
    careerMeaning: 'Defense forces, emergency medicine/surgery, competitive athletics, real estate development, crisis leadership.',
    wealthMeaning: 'Aggressive wealth building through bold ventures, physical property, and courageous executive deals.',
    relationshipMeaning: 'Intensely protective and devoted; requires a calm, grounded domestic partner who de-escalates heated moments.',
    spiritualMeaning: 'Karma yoga of the warrior; protecting the vulnerable and upholding dharma with fearless conviction.',
    remedy: 'Recite Hanuman Chalisa; practice cooling breathwork (Sheetali); donate red lentils or blankets to homeless shelters on Tuesdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 2-SERIES (Moon Mulank)
  '2-1': {
    code: '2-1',
    mulank: 2,
    bhagyank: 1,
    planetaryPair: 'Moon - Sun',
    title: 'The Diplomatic Sovereign / Moon-Sun (चन्द्र-सूर्य समन्वय योग)',
    positiveMeaning: 'Graceful authority, intuitive perception combined with decisive execution, emotional poise, high creativity, and public empathy.',
    negativeMeaning: 'Mood sensitivity impacting professional decisions, internal emotional tug-of-war, financial leakage under emotional duress.',
    careerMeaning: 'Public relations, institutional administration, artistic direction, human resources, diplomatic governance.',
    wealthMeaning: 'Solid, reliable wealth through cooperative alliances, public goodwill, and institutional leadership.',
    relationshipMeaning: 'Supportive, nurturing, and proud of partner’s achievements; balances affection with family dignity.',
    spiritualMeaning: 'Harmonization of emotional mind (Manas) and spiritual soul (Atman).',
    remedy: 'Drink water from silver tumbler; honor both parents equally; practice morning meditation.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-2': {
    code: '2-2',
    mulank: 2,
    bhagyank: 2,
    planetaryPair: 'Moon - Moon',
    title: 'The Deep Intuitive Ocean / Moon-Moon (चन्द्र-चन्द्र रस योग)',
    positiveMeaning: 'Profound empathy, poetic sensitivity, artistic genius, supernatural intuitive radar, gentle healing presence.',
    negativeMeaning: 'Severe mood swings, vulnerability to depression, indecisiveness, overthinking, co-dependency, fear of rejection.',
    careerMeaning: 'Creative writing, psychology, counseling, dairy/beverages, child care, fine arts, nursing, holistic wellness.',
    wealthMeaning: 'Fluctuating liquidity; requires structured automated savings and conservative investing to avoid emotional expenditure.',
    relationshipMeaning: 'Fiercely loving and romantic, but requires constant emotional reassurance and gentle handling.',
    spiritualMeaning: 'Devotional surrender (Bhakti); deep connection to lunar rhythms and fluid cosmic consciousness.',
    remedy: 'Avoid late nights near water bodies; wear a pearl in silver; meditate on full moon; drink water from silver vessel.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-3': {
    code: '2-3',
    mulank: 2,
    bhagyank: 3,
    planetaryPair: 'Moon - Jupiter',
    title: 'The Sage Peacemaker / Gajakesari Yog (गजकेसरी प्रज्ञा योग)',
    positiveMeaning: 'Extraordinary moral reputation, wisdom, gentle advisory power, universal respect, academic brilliance, and emotional nobility.',
    negativeMeaning: 'Over-optimism, trusting unworthy people, neglecting personal boundaries, hesitation to demand deserved compensation.',
    careerMeaning: 'Teaching, holistic counseling, judicial mediation, ethical banking, social reform, literature, spiritual mentorship.',
    wealthMeaning: 'Auspicious, dharmic wealth that brings peace of mind, family prosperity, and long-term security.',
    relationshipMeaning: 'Nurturing, wise, and profoundly loyal companion; establishes a loving, culturally rich household.',
    spiritualMeaning: 'Spiritual illumination through emotional devotion and philosophical wisdom (Gajakesari vibration).',
    remedy: 'Apply saffron tilak; feed cows with soaked chana dal and jaggery on Thursdays; respect spiritual mentors.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-4': {
    code: '2-4',
    mulank: 2,
    bhagyank: 4,
    planetaryPair: 'Moon - Rahu',
    title: 'The Psychological Depths / Grahan Dosh (ग्रहण व क्रांति योग)',
    positiveMeaning: 'Deep psychological depth, ability to pierce illusions, unorthodox creative vision, uncanny instinct for hidden human motivations.',
    negativeMeaning: 'Mental anxiety, sudden phobias, recurring sleep disturbances, emotional turbulence, struggle with trust.',
    careerMeaning: 'Psychiatric medicine, cinema direction, deep psychological fiction, investigative analytics, shadow research.',
    wealthMeaning: 'Unpredictable cash flows; requires strict avoidance of speculative shortcuts and disciplined legal accounting.',
    relationshipMeaning: 'Intense emotional attachments prone to sudden misunderstandings; needs a highly stabilizing, grounded partner.',
    spiritualMeaning: 'Transforming hidden subconscious fears into piercing spiritual awareness and psychological liberation.',
    remedy: 'Worship Lord Shiva (Maha Mrityunjaya mantra); feed dogs on Saturdays; avoid smoky environments; keep silver coin.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-5': {
    code: '2-5',
    mulank: 2,
    bhagyank: 5,
    planetaryPair: 'Moon - Mercury',
    title: 'The Charming Communicator / Moon-Mercury (चन्द्र-बुध सौम्य योग)',
    positiveMeaning: 'Quick wit, emotional charm, adaptability, fluid commercial instinct, social ease, versatile learning, and storytelling flair.',
    negativeMeaning: 'Fickle mindedness, restlessness, scattered focus, and difficulty making deep long-term commitments under stress.',
    careerMeaning: 'Marketing communications, luxury event curation, travel journalism, trading, digital content creation, public relations.',
    wealthMeaning: 'Liquid wealth through smart communication, commission trade, and expansive networking contacts.',
    relationshipMeaning: 'Fun-loving, witty, and engaging; needs variety, intellectual stimulation, and lighthearted communication.',
    spiritualMeaning: 'Balancing the emotional heart and analytical mind in graceful synthesis.',
    remedy: 'Feed green vegetables to birds; practice mindfulness in nature; chant OM BUDHAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-6': {
    code: '2-6',
    mulank: 2,
    bhagyank: 6,
    planetaryPair: 'Moon - Venus',
    title: 'The Aesthetic Romantic / Moon-Venus (चन्द्र-शुक्र सौंदर्य योग)',
    positiveMeaning: 'Exquisite aesthetic taste, magnetism, romantic devotion, luxury comforts, artistic charm, and domestic hospitality.',
    negativeMeaning: 'Over-indulgence, emotional vulnerability in love affairs, avoidance of hard conflict, expenditure on fleeting luxuries.',
    careerMeaning: 'Interior design, fashion styling, hospitality, culinary arts, beauty aesthetics, creative visual arts.',
    wealthMeaning: 'Attracts beautiful residential properties, fine jewelry, and luxury assets; thrives in lifestyle industries.',
    relationshipMeaning: 'Deeply romantic, tender, and caring; creates a warm, opulent home sanctuary for family.',
    spiritualMeaning: 'Channeling divine love and beauty through creative arts and selfless service.',
    remedy: 'Donate white flowers or sweets on Fridays; respect women in family and society; maintain elegant living space.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-7': {
    code: '2-7',
    mulank: 2,
    bhagyank: 7,
    planetaryPair: 'Moon - Ketu',
    title: 'The Mystic Seer / Moon-Ketu (चन्द्र-केतु वैराग्य योग)',
    positiveMeaning: 'Psychic sensitivity, lucid dreaming, philosophical detachment, deep research ability, profound spiritual intuition.',
    negativeMeaning: 'Feeling isolated, mood melancholia, difficulty connecting with mundane crowds, vulnerability to misunderstandings.',
    careerMeaning: 'Alternative healing, occult research, esoteric philosophy, clinical psychology, forensics, deep analytical coding.',
    wealthMeaning: 'Wealth through specialized unique wisdom, confidential consultations, and independent research.',
    relationshipMeaning: 'Needs quiet companionship and soul-level honesty; dislikes social pretension or superficial gossip.',
    spiritualMeaning: 'Rapid path toward inner liberation (Moksha) through emotional transcendence and meditation.',
    remedy: 'Worship Lord Ganesha; keep silver coin in pocket; donate blankets to needy; practice daily silent prayer.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-8': {
    code: '2-8',
    mulank: 2,
    bhagyank: 8,
    planetaryPair: 'Moon - Saturn',
    title: 'The Patient Anchor / Moon-Saturn (चन्द्र-शनि तपस्या योग)',
    positiveMeaning: 'Deep emotional resilience, quiet patience, realism, ability to handle intense grief or hardship, unwavering steadfastness.',
    negativeMeaning: 'Melancholy, chronic overthinking, delayed emotional gratification, feeling burdened by ancestral responsibilities.',
    careerMeaning: 'Administrative operations, institutional property management, long-term rehabilitation, public infrastructure.',
    wealthMeaning: 'Slow, steady accumulation of land, physical properties, and tangible long-term assets over time.',
    relationshipMeaning: 'Extremely loyal and steady; takes time to open up emotionally, requires patience and emotional safety.',
    spiritualMeaning: 'Purification of soul through emotional forbearance, selfless service, and karma yoga.',
    remedy: 'Serve elderly people; chant OM NAMAH SHIVAYA; avoid wearing dark black clothes on Mondays; light oil lamp.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '2-9': {
    code: '2-9',
    mulank: 2,
    bhagyank: 9,
    planetaryPair: 'Moon - Mars',
    title: 'The Passionate Protector / Moon-Mars (चन्द्र-मंगल शक्ति योग)',
    positiveMeaning: 'High emotional courage, protective generosity, dynamic drive, entrepreneurial zest, and humanitarian defense.',
    negativeMeaning: 'Emotional volatility, quick temper, impulsiveness in romantic arguments, digestive heat.',
    careerMeaning: 'Emergency nursing/medicine, real estate sales, sports psychology, social welfare, property management.',
    wealthMeaning: 'Strong earning power and physical asset acquisition through swift initiative and decisive negotiations.',
    relationshipMeaning: 'Passionate and fiercely protective; needs a calm, grounded domestic partner who balances their fiery heart.',
    spiritualMeaning: 'Transformation of raw passion into divine humanitarian service and courageous charity.',
    remedy: 'Drink water from clay pot or silver vessel; avoid overly spicy food; recite Hanuman Chalisa; donate to veterans.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 3-SERIES (Jupiter Mulank)
  '3-1': {
    code: '3-1',
    mulank: 3,
    bhagyank: 1,
    planetaryPair: 'Jupiter - Sun',
    title: 'The Royal Counselor / Guru-Surya (गुरु-सूर्य शासन योग)',
    positiveMeaning: 'Supreme administrative wisdom, ethical authority, scholarly dignity, inspiring mentorship, and societal prestige.',
    negativeMeaning: 'Intellectual pride, rigidity in accepting differing viewpoints, reluctance to accept subordinate roles.',
    careerMeaning: 'Civil administration, university leadership, higher judiciary, corporate governance, spiritual institutions.',
    wealthMeaning: 'Substantial wealth generated through intellectual authority, governmental recognition, and ethical enterprise.',
    relationshipMeaning: 'Noble and honorable partner; expects mutual dignity, intellectual companionship, and shared family values.',
    spiritualMeaning: 'Unification of divine wisdom and sovereign will to guide society along righteous paths.',
    remedy: 'Apply yellow saffron tilak daily; honor teachers and father figures; donate books to students.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-2': {
    code: '3-2',
    mulank: 3,
    bhagyank: 2,
    planetaryPair: 'Jupiter - Moon',
    title: 'The Sovereign Peacemaker / Gajakesari (गुरु-चन्द्र गजकेसरी योग)',
    positiveMeaning: 'Gentle brilliance, emotional intelligence, profound compassion, diplomatic wisdom, and universal respect.',
    negativeMeaning: 'Overly trusting nature, vulnerability to emotional exploitation, difficulty asserting harsh boundaries.',
    careerMeaning: 'Education, psychological therapy, humanitarian leadership, fine literature, diplomatic mediation, healthcare.',
    wealthMeaning: 'Continuous, peaceful prosperity; attracts generous patrons and stable family assets.',
    relationshipMeaning: 'Deeply devoted, affectionate, and spiritually harmonized companion; creates a tranquil home.',
    spiritualMeaning: 'Bhakti-Jnana synthesis; awakening the divine feminine wisdom and devotional peace.',
    remedy: 'Drink water from silver tumbler; respect elders; offer soaked chana dal and jaggery to cows on Thursdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-3': {
    code: '3-3',
    mulank: 3,
    bhagyank: 3,
    planetaryPair: 'Jupiter - Jupiter',
    title: 'The High Sage / Double Guru (गुरु-गुरु ज्ञान योग)',
    positiveMeaning: 'Boundless scholarly wisdom, educational mastery, philosophical authority, oratorical eloquence, and spiritual depth.',
    negativeMeaning: 'Over-talking, dogmatism, weight gain tendencies, ungrounded idealism, neglecting physical health.',
    careerMeaning: 'Professorship, spiritual mentorship, textbook authoring, institutional counseling, judicial leadership.',
    wealthMeaning: 'Prosperity through educational royalties, institutional trusts, and high-level advisory honors.',
    relationshipMeaning: 'Kind, philosophical, and culturally rooted; seeks an intellectually stimulating partner.',
    spiritualMeaning: 'Realization of the higher self through contemplation of scripture and sacred knowledge.',
    remedy: 'Observe silence (Maun Vrat) for 1 hour on Thursdays; wear yellow clothing; avoid excess sweets; respect gurus.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-4': {
    code: '3-4',
    mulank: 3,
    bhagyank: 4,
    planetaryPair: 'Jupiter - Rahu',
    title: 'The Unconventional Thinker / Guru-Chandal (गुरु-राहु क्रांति योग)',
    positiveMeaning: 'Breakthrough intellectual disruption, revolutionary theories, technical mastery, and ability to expose dogmatic fallacies.',
    negativeMeaning: 'Skepticism, friction with traditional mentors, unexpected career shifts, risk of sudden misunderstandings.',
    careerMeaning: 'Data science, advanced electronics research, forensic auditing, investigative philosophy, patent law.',
    wealthMeaning: 'Fluctuating income with sudden massive windfalls; requires systematic long-term wealth locking.',
    relationshipMeaning: 'Independent and non-conformist; requires partner who embraces unconventional lifestyles.',
    spiritualMeaning: 'Piercing dogmatic religious illusions to discover universal, raw cosmic truth.',
    remedy: 'Chant OM RAHAVE NAMAH; feed stray dogs on Saturdays; respect genuine spiritual teachers.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-5': {
    code: '3-5',
    mulank: 3,
    bhagyank: 5,
    planetaryPair: 'Jupiter - Mercury',
    title: 'The Intellectual Merchant / Budha-Guru (गुरु-बुध प्रज्ञा योग)',
    positiveMeaning: 'Extraordinary versatility, rapid analytical brilliance, communicative eloquence, commercial and academic mastery.',
    negativeMeaning: 'Restless intellect, scattered projects, mental over-stimulation, nervous exhaustion.',
    careerMeaning: 'Publishing, higher educational administration, corporate strategy, international law, digital media trade.',
    wealthMeaning: 'Multiple revenue streams, commercial agility, lucrative consulting, and rapid market success.',
    relationshipMeaning: 'Witty, vibrant, communicative, and intellectually joyful partner; dislikes dull routines.',
    spiritualMeaning: 'Bridging the practical worldly intellect with divine philosophical understanding.',
    remedy: 'Plant holy basil (Tulsi) or green trees; feed green grass to cows; chant OM GURAVE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-6': {
    code: '3-6',
    mulank: 3,
    bhagyank: 6,
    planetaryPair: 'Jupiter - Venus',
    title: 'The Dual Mentor Dynamic / Devaguru-Daityaguru (देवगुरु-दैत्यगुरु योग)',
    positiveMeaning: 'Supreme creative refinement, mastery of both spiritual and material arts, immense cultural taste, and charm.',
    negativeMeaning: 'Internal conflict between ascetic discipline and luxury indulgence; romantic idealism causing disillusionment.',
    careerMeaning: 'High-end cinema, luxury architecture, arts administration, marriage counseling, cultural diplomatic roles.',
    wealthMeaning: 'Wealth generated through creative genius, design patents, and aesthetic entertainment.',
    relationshipMeaning: 'Romantic yet ethically grounded; seeks an artistic, refined, and emotionally devoted spouse.',
    spiritualMeaning: 'Balancing the higher philosophical intellect with earthly compassion and sensual aesthetic joy.',
    remedy: 'Respect both male and female mentors; donate white sweets to students; maintain clean aesthetic living.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-7': {
    code: '3-7',
    mulank: 3,
    bhagyank: 7,
    planetaryPair: 'Jupiter - Ketu',
    title: 'The Spiritual Ascetic / Guru-Ketu (गुरु-केतु मोक्ष योग)',
    positiveMeaning: 'Profound metaphysical intuition, deep scriptural research, spiritual detachment, wisdom, and forensic mastery.',
    negativeMeaning: 'Indifference to commercial ambition, feeling alien in corporate settings, social aloofness.',
    careerMeaning: 'Spiritual research, astrology/occult science, clinical psychology, philosophical authorship, solitary R&D.',
    wealthMeaning: 'Modest to substantial wealth earned primarily through specialized advisory, research, and non-commercial channels.',
    relationshipMeaning: 'Values deep quiet companionship and sacred spiritual alignment over worldly displays.',
    spiritualMeaning: 'Supreme alignment for spiritual liberation (Moksha), inner awakening, and transcendental knowledge.',
    remedy: 'Worship Lord Ganesha; practice meditation; donate blankets or winter clothes to sadhus or needy individuals.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-8': {
    code: '3-8',
    mulank: 3,
    bhagyank: 8,
    planetaryPair: 'Jupiter - Saturn',
    title: 'The Dharmic Judge / Guru-Shani (गुरु-शनि न्याय योग)',
    positiveMeaning: 'Impeccable ethical integrity, judicial wisdom, disciplined scholarship, steadfast patience, and executive stature.',
    negativeMeaning: 'Strict rigidity, heavy burden of responsibility, severe self-criticism, delayed rewards.',
    careerMeaning: 'Judiciary, constitutional law, corporate compliance, institutional leadership, history, civil engineering.',
    wealthMeaning: 'Solid, enduring wealth accumulated over decades of structured service; zero vulnerability to fraud.',
    relationshipMeaning: 'Serious, loyal, protective, and deeply responsible; values marital commitment and family honor.',
    spiritualMeaning: 'Mastery of Karma Yoga through righteous duty, justice, and selfless institutional service.',
    remedy: 'Help underprivileged students with study materials; light mustard oil lamp under Peepal tree on Saturdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '3-9': {
    code: '3-9',
    mulank: 3,
    bhagyank: 9,
    planetaryPair: 'Jupiter - Mars',
    title: 'The Righteous Warrior / Guru-Mangal (गुरु-मंगल शौर्य योग)',
    positiveMeaning: 'Courageous defense of truth, high moral bravery, dynamic academic drive, inspiring executive energy, and generosity.',
    negativeMeaning: 'Dogmatic aggression, quick temper when principles are questioned, intolerance for sluggish bureaucracy.',
    careerMeaning: 'Military academy leadership, medical surgery, judicial enforcement, civil rights advocacy, sports coaching.',
    wealthMeaning: 'High earning capacity through courageous initiatives, land/asset acquisitions, and pioneering projects.',
    relationshipMeaning: 'Passionate, honorable, protective, and energetic; expects honesty and mutual ambition.',
    spiritualMeaning: 'Active righteous crusade (Dharmayuddha); defending the defenseless with spiritual courage.',
    remedy: 'Recite Hanuman Chalisa; apply saffron or red sandalwood tilak; support athletic or martial arts students.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 4-SERIES (Rahu Mulank)
  '4-1': {
    code: '4-1',
    mulank: 4,
    bhagyank: 1,
    planetaryPair: 'Rahu - Sun',
    title: 'The Unorthodox Leader / Rahu-Surya (राहु-सूर्य क्रांति योग)',
    positiveMeaning: 'Radical innovation, commanding unconventional authority, technological breakthroughs, bold strategic risks.',
    negativeMeaning: 'Public controversies, clashes with governmental regulators, hidden adversaries, sudden reputation swings.',
    careerMeaning: 'Cutting-edge tech ventures, mass digital media, political disruptor, frontier aerospace, international trade.',
    wealthMeaning: 'Rapid sudden wealth cycles; must institute strict legal oversight and conservative reserves.',
    relationshipMeaning: 'Demands personal independence; needs a confident, self-sufficient partner who can ride out public waves.',
    spiritualMeaning: 'Awakening soul sovereignty by shattering conventional social pretenses and limiting beliefs.',
    remedy: 'Offer water to the morning sun; feed stray dogs on Saturdays; chant OM SURYAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-2': {
    code: '4-2',
    mulank: 4,
    bhagyank: 2,
    planetaryPair: 'Rahu - Moon',
    title: 'The Restless Visionary / Rahu-Chandra (राहु-चन्द्र ग्रहण योग)',
    positiveMeaning: 'Exceptional artistic imagination, uncanny psychological perception, ability to understand mass desires and trends.',
    negativeMeaning: 'Chronic anxiety, insomnia, emotional volatility, difficulty establishing emotional security, over-imagination.',
    careerMeaning: 'Cinematography, viral advertising, psychological thrillers, shadow analytics, deep underwater/fluid research.',
    wealthMeaning: 'Fluctuating liquidity; requires automated financial safeguards and cautious investment partnerships.',
    relationshipMeaning: 'Intense emotional highs and lows; requires an exceptionally calm, reassuring, and grounded partner.',
    spiritualMeaning: 'Transforming psychological turbulence into profound spiritual compassion and detachment.',
    remedy: 'Drink water from silver tumbler; chant Maha Mrityunjaya Mantra; avoid solitude during dark moon nights.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-3': {
    code: '4-3',
    mulank: 4,
    bhagyank: 3,
    planetaryPair: 'Rahu - Jupiter',
    title: 'The Iconoclastic Scholar / Rahu-Guru (राहु-गुरु विप्लव योग)',
    positiveMeaning: 'Unconventional wisdom, capability to pioneer new academic disciplines, breakthrough technical coaching.',
    negativeMeaning: 'Tendency to dispute established authorities, skepticism, risk of academic or organizational disputes.',
    careerMeaning: 'Advanced research technology, cross-cultural studies, patent consultation, fintech architecture, educational reforms.',
    wealthMeaning: 'Substantial wealth generated through specialized proprietary methodologies and non-traditional coaching.',
    relationshipMeaning: 'Stimulating, open-minded, and intellectually adventurous; dislikes traditional domestic constraints.',
    spiritualMeaning: 'Deconstructing dogmas to discover authentic spiritual liberation and cosmic order.',
    remedy: 'Honor genuine gurus; donate yellow items or books to underprivileged students; chant OM GURAVE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-4': {
    code: '4-4',
    mulank: 4,
    bhagyank: 4,
    planetaryPair: 'Rahu - Rahu',
    title: 'The Double Lightning Forge / Double Rahu (राहु-राहु विद्युत योग)',
    positiveMeaning: 'Extreme technical brilliance, ability to work relentlessly in complex systems, unconventional mastermind, radical ambition.',
    negativeMeaning: 'Severe mental exhaustion, chronic stress, illusionary goals, alienation, sudden sharp setbacks.',
    careerMeaning: 'Cybersecurity, artificial intelligence, cryptographic systems, advanced digital engineering, international intelligence.',
    wealthMeaning: 'Erratic cash flows; needs strict non-speculative wealth managers to avoid catastrophic impulsive gambles.',
    relationshipMeaning: 'Highly solitary and unpredictable; needs an exceptionally patient, independent partner.',
    spiritualMeaning: 'Overcoming the ultimate matrix of material illusion (Maya) through profound self-mastery.',
    remedy: 'Keep physical terrace clean; feed stray dogs daily; practice grounding bare-foot walking; avoid alcohol and smoking.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-5': {
    code: '4-5',
    mulank: 4,
    bhagyank: 5,
    planetaryPair: 'Rahu - Mercury',
    title: 'The High-Frequency Trader / Rahu-Budha (राहु-बुध चातुर्य योग)',
    positiveMeaning: 'Unmatched speed of calculation, brilliant digital trading instincts, master networking, sharp commercial acumen.',
    negativeMeaning: 'Nervous restlessness, over-clever shortcuts leading to legal entanglements, difficulty slowing down.',
    careerMeaning: 'Algorithmic trading, fintech innovation, mass PR, digital advertising, software development, e-commerce.',
    wealthMeaning: 'Rapid capital compounding through digital transactions and innovative modern commerce.',
    relationshipMeaning: 'Dynamic, fast-paced, humorous, and witty; thrives with an agile and communicative partner.',
    spiritualMeaning: 'Mastering the etheric frequencies of human communication and aligning them with higher truth.',
    remedy: 'Feed green grass to cows on Wednesdays; practice digital detox on weekends; chant OM BUDHAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-6': {
    code: '4-6',
    mulank: 4,
    bhagyank: 6,
    planetaryPair: 'Rahu - Venus',
    title: 'The Glamour & Media Magnet / Rahu-Shukra (राहु-शुक्र आकर्षण योग)',
    positiveMeaning: 'Mesmerizing charisma, viral media success, lavish aesthetic innovation, mastery of modern entertainment and luxury trends.',
    negativeMeaning: 'Risk of scandals, extravagant wasteful expenditures, superficial entanglements, lifestyle burnout.',
    careerMeaning: 'Entertainment industry, modeling, luxury hospitality, fashion technology, cosmetic dermatology, high-end cinema.',
    wealthMeaning: 'Tremendous influx of wealth through mass popularity and luxury branding; must guard against luxury leakage.',
    relationshipMeaning: 'Passionate and glamorous; needs grounding in deep moral loyalty to prevent superficial drift.',
    spiritualMeaning: 'Recognizing that all worldly glamour is fleeting, seeking lasting inner beauty.',
    remedy: 'Donate white sweets or cosmetics to underprivileged women on Fridays; maintain strict moral discipline.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-7': {
    code: '4-7',
    mulank: 4,
    bhagyank: 7,
    planetaryPair: 'Rahu - Ketu',
    title: 'The Cosmic Axis / Rahu-Ketu (राहु-केतु नाग योग)',
    positiveMeaning: 'Profound metaphysical penetration, mastery of esoteric systems, uncanny diagnostic instincts, spiritual polarity.',
    negativeMeaning: 'Feeling detached from worldly reality, unexplainable physical symptoms, recurring sense of cosmic isolation.',
    careerMeaning: 'Occult forensics, alternative healing, advanced quantum research, deep medical diagnostics, cyber forensics.',
    wealthMeaning: 'Unconventional wealth acquisition; money flows best when pursuing spiritual or deep investigative callings.',
    relationshipMeaning: 'Mysterious and solitary; requires a partner who understands sacred solitude and metaphysical pursuits.',
    spiritualMeaning: 'Direct integration of the head (Rahu) and tail (Ketu) of the cosmic serpent; awakening of Kundalini energy.',
    remedy: 'Worship Lord Ganesha and Lord Shiva; feed stray animals; practice pranayama and grounding dhyana.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-8': {
    code: '4-8',
    mulank: 4,
    bhagyank: 8,
    planetaryPair: 'Rahu - Saturn',
    title: 'The Steel Karmic Crucible / Rahu-Shani (राहु-शनि वज्र योग)',
    positiveMeaning: 'Immense stamina, relentless perseverance, unshakeable resilience against hardships, technical mastery of heavy systems.',
    negativeMeaning: 'Severe early struggles, heavy delays, risk of legal complications or bone/joint strain, feeling burdened.',
    careerMeaning: 'Heavy engineering, mining, industrial manufacturing, corporate turnaround management, judicial administration.',
    wealthMeaning: 'Hard-earned permanent wealth; builds monumental physical assets after navigating rigorous early trials.',
    relationshipMeaning: 'Extremely serious, cautious, and steadfast; takes time to build emotional trust and intimacy.',
    spiritualMeaning: 'Deep karmic cleansing through enduring patience, selfless service, and humble labor.',
    remedy: 'Serve manual laborers on Saturdays; light mustard oil lamp under Peepal tree; feed black dogs; maintain rigorous integrity.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '4-9': {
    code: '4-9',
    mulank: 4,
    bhagyank: 9,
    planetaryPair: 'Rahu - Mars',
    title: 'The High-Voltage Dynamo / Rahu-Mangal (राहु-मंगल अंगारक योग)',
    positiveMeaning: 'Unstoppable physical energy, daring courage, fearless execution, ability to manage high-stakes emergency crises.',
    negativeMeaning: 'Extreme temper flare-ups, impulsiveness, proneness to accidents or fiery conflicts, legal friction.',
    careerMeaning: 'Defense intelligence, emergency surgical operations, dangerous expeditions, high-risk competitive athletics, demolition.',
    wealthMeaning: 'Aggressive wealth capture through high-risk daring enterprises; requires conservative risk management.',
    relationshipMeaning: 'Intense and tempestuous; needs a partner with exceptional emotional stability and cooling energy.',
    spiritualMeaning: 'Transmuting raw fiery aggression into disciplined spiritual valor and protection of the helpless.',
    remedy: 'Recite Hanuman Chalisa daily; avoid rash driving; donate blood periodically; avoid red hot spices.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 5-SERIES (Mercury Mulank)
  '5-1': {
    code: '5-1',
    mulank: 5,
    bhagyank: 1,
    planetaryPair: 'Mercury - Sun',
    title: 'The Dynamic Entrepreneur / Budha-Surya (बुध-सूर्य बुधादित्य योग)',
    positiveMeaning: 'Superb commercial vision, articulate sovereign leadership, rapid executive action, sharp mercantile intellect.',
    negativeMeaning: 'Restlessness, impatience with bureaucracy, over-committing to multiple commercial initiatives.',
    careerMeaning: 'Corporate founder, international trade, media publishing, executive advisory, venture capital.',
    wealthMeaning: 'Rapid and sustained wealth creation through innovative commercial strategies and strong executive brand equity.',
    relationshipMeaning: 'Dynamic, engaging, inspiring, and proud; seeks a partner who shares ambitious worldly goals.',
    spiritualMeaning: 'Using intellectual and commercial gifts to build righteous institutions that benefit society.',
    remedy: 'Offer water to the rising sun; keep green plants in work environment; chant Gayatri Mantra.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-2': {
    code: '5-2',
    mulank: 5,
    bhagyank: 2,
    planetaryPair: 'Mercury - Moon',
    title: 'The Fluid Diplomat / Budha-Chandra (बुध-चन्द्र सौम्य योग)',
    positiveMeaning: 'Charming persuasive diplomacy, emotional rapport, fluid commercial instincts, high communicative flexibility.',
    negativeMeaning: 'Indecisiveness under stress, mood fluctuations impacting business decisions, financial leakage on luxury impulse.',
    careerMeaning: 'Public relations, luxury travel curation, marketing diplomacy, hospitality, media management, creative writing.',
    wealthMeaning: 'Steady liquid income from multiple commercial channels, commissions, and strategic partnerships.',
    relationshipMeaning: 'Gentle, talkative, humorous, and affectionate; creates an inviting, harmonious home atmosphere.',
    spiritualMeaning: 'Harmonizing rational thinking with emotional empathy to foster universal brotherhood.',
    remedy: 'Drink water from silver glass; feed green grass to cows; avoid business deals on new moon days.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-3': {
    code: '5-3',
    mulank: 5,
    bhagyank: 3,
    planetaryPair: 'Mercury - Jupiter',
    title: 'The Scholarly Merchant / Budha-Guru (बुध-गुरु सरस्वती योग)',
    positiveMeaning: 'Exceptional intellectual depth, pedagogical mastery, commercial and legal brilliance, articulate public speech.',
    negativeMeaning: 'Mental restlessness, tendency to scatter focus across too many academic or business interests.',
    careerMeaning: 'Higher educational publishing, corporate training, international commerce law, economic consultancy, journalism.',
    wealthMeaning: 'Prosperity generated through intellectual property, high-level advisory fees, and educational enterprises.',
    relationshipMeaning: 'Respectful, intellectually stimulating, witty, and generous; values meaningful cultural discussions.',
    spiritualMeaning: 'Synthesis of practical intellect and higher divine wisdom for the upliftment of human consciousness.',
    remedy: 'Apply saffron tilak; donate green items on Wednesdays and yellow books on Thursdays; chant OM GURAVE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-4': {
    code: '5-4',
    mulank: 5,
    bhagyank: 4,
    planetaryPair: 'Mercury - Rahu',
    title: 'The Digital Disruptor / Budha-Rahu (बुध-राहु चातुर्य योग)',
    positiveMeaning: 'Uncanny technological speed, master of modern fintech and crypto trends, out-of-the-box marketing genius.',
    negativeMeaning: 'Restlessness, vulnerability to risky speculative ventures, nervous tension, potential legal scrutiny.',
    careerMeaning: 'Software architecture, digital marketing, algorithmic trading, electronic media, cybersecurity, e-commerce.',
    wealthMeaning: 'High liquidity and sudden commercial compounding; requires disciplined financial governance.',
    relationshipMeaning: 'Fast-paced, modern, witty, and independent; thrives with a partner who enjoys rapid change.',
    spiritualMeaning: 'Using modern technological communication to spread illuminating and truthful perspectives.',
    remedy: 'Feed stray dogs and birds; practice grounding exercises; avoid speculative shortcuts; chant OM BUDHAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-5': {
    code: '5-5',
    mulank: 5,
    bhagyank: 5,
    planetaryPair: 'Mercury - Mercury',
    title: 'The Master Trader / Double Mercury (बुध-बुध व्यापार योग)',
    positiveMeaning: 'Supreme communicative speed, lightning calculation, unmatched networking dexterity, versatile commercial mind.',
    negativeMeaning: 'Severe mental restlessness, scattered energy, insomnia, difficulty finishing projects, superficiality.',
    careerMeaning: 'Stock broking, international import-export, investigative journalism, digital media agency, public speaking.',
    wealthMeaning: 'Abundant fluid cash flow; must consciously lock funds into illiquid assets to prevent rapid dispersion.',
    relationshipMeaning: 'Fun, spontaneous, talkative, and lively; needs a calm partner who provides anchoring stability.',
    spiritualMeaning: 'Mastery of speech (Vak Siddhi); directing words exclusively toward truthful and healing outcomes.',
    remedy: 'Feed cows green fodder on Wednesdays; worship Tulsi plant; observe daily digital silence for 1 hour.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-6': {
    code: '5-6',
    mulank: 5,
    bhagyank: 6,
    planetaryPair: 'Mercury - Venus',
    title: 'The Lakshmi Yoga / Wealth Attractor (बुध-शुक्र महालक्ष्मी योग)',
    positiveMeaning: 'Supreme commercial prosperity, luxury branding brilliance, magnetic charm, exquisite design taste, highly lucrative partnerships.',
    negativeMeaning: 'Lavish spending habits, difficulty saying no to luxury temptations, over-indulgence in comfort.',
    careerMeaning: 'Luxury retail, haute couture, cosmetic marketing, high-end event management, interior architecture, film commerce.',
    wealthMeaning: 'Immense wealth attraction; one of the premier combinations for commercial compounding and material luxury.',
    relationshipMeaning: 'Romantic, charming, joyful, and generous; creates an opulent, hospitable, and loving home.',
    spiritualMeaning: 'Experiencing divine abundance as a sacred trust to be shared generously with the community.',
    remedy: 'Donate white sweets to young girls on Fridays; wear clean, pleasant fragrances; worship Goddess Lakshmi.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-7': {
    code: '5-7',
    mulank: 5,
    bhagyank: 7,
    planetaryPair: 'Mercury - Ketu',
    title: 'The Mercury-Ketu Amalgam / Deep Analyst (बुध-केतु शोध योग)',
    positiveMeaning: 'Profound intellectual curiosity, balanced analytical alignment, deep research ability, high execution drive, forensic precision.',
    negativeMeaning: 'Internal conflicts where mercurial restlessness clashes with ketu detachment, over-thinking, nervous strain.',
    careerMeaning: 'Data forensics, specialized scientific research, clinical analytics, esoteric philosophy, confidential advisory.',
    wealthMeaning: 'Steady, structured wealth from specialized mastery and intellectual patents; avoids flashy consumerism.',
    relationshipMeaning: 'Seeks clear, open verbal agreements, empathetic alignment, and quiet emotional companionship.',
    spiritualMeaning: 'Deep self-reflection, high-vibration mentorship, transmuting intellect into spiritual realization.',
    remedy: 'Support homeless shelters or donate woolen clothes on Saturdays; worship Lord Ganesha; practice dhyana.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-8': {
    code: '5-8',
    mulank: 5,
    bhagyank: 8,
    planetaryPair: 'Mercury - Saturn',
    title: 'The Prudent Corporate Strategist / Budha-Shani (बुध-शनि नीति योग)',
    positiveMeaning: 'Calculated business acumen, disciplined financial foresight, deep patience in market execution, enduring commercial systems.',
    negativeMeaning: 'Over-cautiousness causing missed opportunities, dry communication, mental fatigue under prolonged responsibility.',
    careerMeaning: 'Corporate auditing, institutional finance, industrial supply chains, real estate investments, tax consulting.',
    wealthMeaning: 'Highly stable, compounding wealth; builds massive tangible portfolios through methodical, risk-managed discipline.',
    relationshipMeaning: 'Dependable, steady, loyal, and practical; shows love through enduring support and financial security.',
    spiritualMeaning: 'Purifying commerce through ethical duty, fairness to workers, and disciplined stewardship.',
    remedy: 'Feed crows or black dogs on Saturdays; serve manual laborers; chant OM SHAM SHANAISCHARAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '5-9': {
    code: '5-9',
    mulank: 5,
    bhagyank: 9,
    planetaryPair: 'Mercury - Mars',
    title: 'The Tactical Commander / Budha-Mangal (बुध-मंगल युक्ति योग)',
    positiveMeaning: 'Dynamic operational drive, sharp strategic instincts, rapid sales execution, high courage, and problem-solving velocity.',
    negativeMeaning: 'Sharp verbal bluntness, argumentative temper, impulsiveness in commercial negotiations, nervous burnout.',
    careerMeaning: 'High-stakes sales direction, real estate brokerage, technology startup scaling, military logistics, investigative reporting.',
    wealthMeaning: 'Aggressive wealth building; captures market opportunities swiftly through bold calculated initiatives.',
    relationshipMeaning: 'Passionate, energetic, and candid; needs a partner who appreciates direct honesty and high enthusiasm.',
    spiritualMeaning: 'Using intellectual clarity and courage to champion righteous causes and defeat ignorance.',
    remedy: 'Recite Hanuman Chalisa; avoid hasty arguments; donate green items on Wednesdays and red lentils on Tuesdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 6-SERIES (Venus Mulank)
  '6-1': {
    code: '6-1',
    mulank: 6,
    bhagyank: 1,
    planetaryPair: 'Venus - Sun',
    title: 'The Royal Splendor / Shukra-Surya (शुक्र-सूर्य ऐश्वर्य योग)',
    positiveMeaning: 'Commanding glamour, supreme artistic charisma, executive luxury leadership, magnetic social presence.',
    negativeMeaning: 'Ego clashes in romance, extravagance, pride, vulnerability to flattery and superficial admiration.',
    careerMeaning: 'High-end cinema, luxury corporate leadership, brand ambassador, fashion diplomacy, creative direction.',
    wealthMeaning: 'Magnificent wealth generation; commands high commercial value and premium lifestyle assets.',
    relationshipMeaning: 'Lavish, affectionate, and proud; demands mutual respect, fidelity, and aesthetic refinement.',
    spiritualMeaning: 'Using aesthetic beauty and material influence to inspire noble and uplifting societal standards.',
    remedy: 'Donate white clothing to needy girls on Fridays; offer water to the morning sun; wear pleasant fragrance.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-2': {
    code: '6-2',
    mulank: 6,
    bhagyank: 2,
    planetaryPair: 'Venus - Moon',
    title: 'The Aesthetic Romantic / Shukra-Chandra (शुक्र-चन्द्र माधुर्य योग)',
    positiveMeaning: 'Profound artistic sensitivity, domestic harmony, romantic tenderness, magnetic social grace, hospitality mastery.',
    negativeMeaning: 'Hypersensitivity, mood swings affecting financial discipline, difficulty setting emotional boundaries, vanity.',
    careerMeaning: 'Interior design, haute cuisine, fine arts, high-end hospitality, luxury counseling, cosmetic aesthetics.',
    wealthMeaning: 'Continuous accumulation of beautiful residential properties, precious metals, and luxury comfort assets.',
    relationshipMeaning: 'Deeply romantic, nurturing, and devoted; makes family sanctuary the emotional centerpiece of life.',
    spiritualMeaning: 'Experiencing the divine presence through unconditional love, creative beauty, and compassionate care.',
    remedy: 'Drink water from silver glass; donate white flowers or milk on Mondays and Fridays; respect female elders.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-3': {
    code: '6-3',
    mulank: 6,
    bhagyank: 3,
    planetaryPair: 'Venus - Jupiter',
    title: 'The Dual Wisdom Union / Shukra-Guru (शुक्र-गुरु द्वैत योग)',
    positiveMeaning: 'Mastery of both spiritual philosophy and worldly aesthetic arts, supreme cultural erudition, generous mentorship.',
    negativeMeaning: 'Conflict between spiritual discipline and sensual luxury indulgence, over-spending on social celebrations.',
    careerMeaning: 'Cultural leadership, educational foundation director, arts philanthropy, marriage jurisprudence, luxury publishing.',
    wealthMeaning: 'Substantial, honorable prosperity built on creative excellence, teaching, and aesthetic advisory.',
    relationshipMeaning: 'Cultured, noble, loving, and intellectually rich; creates a gracious, hospitable home.',
    spiritualMeaning: 'Reconciling worldly beauty (Shukra) with eternal spiritual truth (Guru) in balanced harmony.',
    remedy: 'Apply yellow sandalwood tilak; donate books and white sweets to students; honor all spiritual traditions.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-4': {
    code: '6-4',
    mulank: 6,
    bhagyank: 4,
    planetaryPair: 'Venus - Rahu',
    title: 'The Avant-Garde Stylist / Shukra-Rahu (शुक्र-राहु सम्मोहन योग)',
    positiveMeaning: 'Magnetic public charm, modern trendsetter, disruptive aesthetic genius, viral lifestyle and media appeal.',
    negativeMeaning: 'Susceptibility to illusions in relationships, sudden emotional disillusionment, extravagant lifestyle leakage.',
    careerMeaning: 'Digital entertainment, fashion technology, media production, cosmetic innovations, viral brand marketing.',
    wealthMeaning: 'Massive sudden influx of luxury capital; requires strict accounting discipline and conservative reserves.',
    relationshipMeaning: 'Intensely passionate, modern, and exciting; must prioritize honest communication and steady loyalty.',
    spiritualMeaning: 'Seeing through the glitter of worldly glamour to recognize the true enduring light within.',
    remedy: 'Worship Goddess Durga; donate white sweets to young girls on Fridays; avoid deceptive shortcuts.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-5': {
    code: '6-5',
    mulank: 6,
    bhagyank: 5,
    planetaryPair: 'Venus - Mercury',
    title: 'The Lakshmi Commerce Engine / Shukra-Budha (शुक्र-बुध महालक्ष्मी योग)',
    positiveMeaning: 'Supreme commercial eloquence, lucrative brand curation, rapid financial growth, charming negotiation, aesthetic brilliance.',
    negativeMeaning: 'Tendency to spend lavishly, restlessness, over-indulgence in lifestyle luxuries.',
    careerMeaning: 'Luxury retail founder, international fashion trade, high-end advertising, public diplomacy, interior styling.',
    wealthMeaning: 'Unrivaled wealth attraction; combines Venusian luxury magnet with Mercurial commercial execution.',
    relationshipMeaning: 'Vibrant, witty, romantic, and charming; brings laughter, style, and hospitality to family life.',
    spiritualMeaning: 'Using material prosperity as an instrument of generosity, public welfare, and community upliftment.',
    remedy: 'Feed cows green grass on Wednesdays; donate fragrant white flowers on Fridays; chant Sri Suktam.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-6': {
    code: '6-6',
    mulank: 6,
    bhagyank: 6,
    planetaryPair: 'Venus - Venus',
    title: 'The Supreme Splendor / Double Venus (शुक्र-शुक्र विलास योग)',
    positiveMeaning: 'Peerless aesthetic taste, supreme artistic gifts, opulent lifestyle, profound romantic devotion, universal charm.',
    negativeMeaning: 'Excessive indulgence, lethargy, avoidance of hard physical exertion, vulnerability to flattery and vanity.',
    careerMeaning: 'Haute couture, fine jewelry design, high-end cinema, luxury resort architecture, cosmetic medicine.',
    wealthMeaning: 'Continuous attraction of premium vehicles, opulent real estate, and high-net-worth aesthetic patronage.',
    relationshipMeaning: 'Deeply affectionate, romantic, and dedicated to luxury comfort; needs a partner who values fine living.',
    spiritualMeaning: 'Transforming sensory beauty into supreme devotional love (Prem Yoga) for the Divine.',
    remedy: 'Practice dietary fasting or moderation on Fridays; donate white garments; chant OM SHUKRAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-7': {
    code: '6-7',
    mulank: 6,
    bhagyank: 7,
    planetaryPair: 'Venus - Ketu',
    title: 'The Spiritualized Artist / Shukra-Ketu (शुक्र-केतु वैराग्य-सौंदर्य योग)',
    positiveMeaning: 'Deep spiritual aesthetic vision, sacred art, mystical intuition, refined discernment, emotional authenticity.',
    negativeMeaning: 'Sudden disillusionment with romantic partners, feelings of emotional detachment, solitude tendencies.',
    careerMeaning: 'Sacred architectural design, classical musical composition, esoteric wellness, holistic beauty therapy.',
    wealthMeaning: 'Substantial wealth derived from unique, specialized creative mastery and independent artistic production.',
    relationshipMeaning: 'Values soul-level authenticity, spiritual kinship, and mutual personal space over mundane romance.',
    spiritualMeaning: 'Elevating aesthetic appreciation into transcendent meditation and detachment from material bondage.',
    remedy: 'Worship Lord Ganesha; donate blankets to the needy; chant OM GUM GANAPATAYE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-8': {
    code: '6-8',
    mulank: 6,
    bhagyank: 8,
    planetaryPair: 'Venus - Saturn',
    title: 'The Material Architect / Shukra-Shani (शुक्र-शनि स्थायित्व योग)',
    positiveMeaning: 'Enduring material structures, pragmatic design mastery, deep patience in asset accumulation, loyalty in partnership.',
    negativeMeaning: 'Delayed romantic fulfillment, emotional seriousness, heavy domestic burdens, tendency toward melancholy.',
    careerMeaning: 'Real estate development, civil architecture, industrial design, luxury vintage trading, corporate law.',
    wealthMeaning: 'Permanent, compounded wealth; builds massive physical real estate and tangible assets over decades.',
    relationshipMeaning: 'Extremely loyal, protective, and steadfast; expresses love through reliable practical care and security.',
    spiritualMeaning: 'Harmonizing sensual aesthetic beauty with karmic discipline and selfless duty.',
    remedy: 'Serve elderly women on Saturdays; light sesame or mustard oil lamp; wear clean blue or off-white garments.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '6-9': {
    code: '6-9',
    mulank: 6,
    bhagyank: 9,
    planetaryPair: 'Venus - Mars',
    title: 'The Passionate Catalyst / Shukra-Mangal (शुक्र-मंगल आकर्षण योग)',
    positiveMeaning: 'Intense charismatic magnetism, creative courage, passionate drive, generous humanitarian philanthropy.',
    negativeMeaning: 'Emotional volatility, heated arguments in intimate relationships, impulsive financial spending.',
    careerMeaning: 'Dramatic performing arts, luxury sports management, cosmetic surgery, real estate marketing, hospitality scaling.',
    wealthMeaning: 'Dynamic earning capacity; attracts substantial capital through bold creative and property investments.',
    relationshipMeaning: 'Fiercely passionate and protective; requires clear emotional boundaries and cooling domestic practices.',
    spiritualMeaning: 'Channeling intense vital passion into courageous humanitarian work and divine devotional service.',
    remedy: 'Drink water from clay vessels; practice cooling pranayama (Sheetali); recite Hanuman Chalisa on Tuesdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 7-SERIES (Ketu Mulank)
  '7-1': {
    code: '7-1',
    mulank: 7,
    bhagyank: 1,
    planetaryPair: 'Ketu - Sun',
    title: 'The Introspective Sovereign / Ketu-Surya (केतु-सूर्य आत्म योग)',
    positiveMeaning: 'Deep spiritual authority, introspective research mastery, unshakeable individual integrity, quiet societal dignity.',
    negativeMeaning: 'Feeling alienated from mainstream politics, sudden career detachments, reluctance to play corporate games.',
    careerMeaning: 'Scientific research, deep forensics, independent strategic consultancy, metaphysical philosophy, surgery.',
    wealthMeaning: 'Wealth generated through unique proprietary expertise, intellectual patents, and high-level confidential advice.',
    relationshipMeaning: 'Needs quiet companionship, mutual respect for personal space, and freedom from superficial social demands.',
    spiritualMeaning: 'Direct realization of the immortal soul (Atman) transcending transient worldly identities.',
    remedy: 'Offer water to the morning sun; worship Lord Ganesha; donate woolen blankets to homeless elders on Saturdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-2': {
    code: '7-2',
    mulank: 7,
    bhagyank: 2,
    planetaryPair: 'Ketu - Moon',
    title: 'The Mystic Seer / Ketu-Chandra (केतु-चन्द्र वैराग्य योग)',
    positiveMeaning: 'Profound intuitive radar, psychic sensitivity, lucid spiritual vision, poetic depth, compassionate healing touch.',
    negativeMeaning: 'Vulnerability to mood depression, emotional loneliness, overthinking, difficulty in mundane emotional bonding.',
    careerMeaning: 'Alternative psychotherapy, clinical counseling, dream analysis, esoteric research, fine arts, palliative care.',
    wealthMeaning: 'Modest to solid wealth; thrives best when finances are automated and protected from emotional impulses.',
    relationshipMeaning: 'Seeks a soulmate connection; requires a deeply empathetic, patient, and non-judgmental partner.',
    spiritualMeaning: 'Transcending emotional attachments to attain supreme devotional peace and spiritual detachment.',
    remedy: 'Drink water from a silver cup; chant Maha Mrityunjaya Mantra; keep a pure silver coin in wallet.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-3': {
    code: '7-3',
    mulank: 7,
    bhagyank: 3,
    planetaryPair: 'Ketu - Jupiter',
    title: 'The High Metaphysician / Ketu-Guru (केतु-गुरु मोक्ष योग)',
    positiveMeaning: 'Supreme philosophical illumination, scriptural authority, spiritual teaching gifts, unshakeable moral compass.',
    negativeMeaning: 'Disdain for mundane materialism, reluctance to monetize sacred knowledge, intellectual detachment.',
    careerMeaning: 'Spiritual authorship, university philosophy leadership, specialized occult sciences, clinical bio-research.',
    wealthMeaning: 'Prosperity comes naturally as a byproduct of genuine spiritual and intellectual service to humanity.',
    relationshipMeaning: 'Honorable, deeply peaceful, and culturally rooted; seeks a partner who shares higher values.',
    spiritualMeaning: 'Supreme combination for liberation (Moksha) and direct transmission of sacred wisdom.',
    remedy: 'Apply yellow saffron tilak daily; honor gurus; donate educational books to poor children on Thursdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-4': {
    code: '7-4',
    mulank: 7,
    bhagyank: 4,
    planetaryPair: 'Ketu - Rahu',
    title: 'The Occult Polarity / Ketu-Rahu (केतु-राहु चक्र योग)',
    positiveMeaning: 'Uncanny diagnostic genius, ability to operate on the boundary between physical and metaphysical, profound research.',
    negativeMeaning: 'Unexplained life reversals, feeling trapped between material desire and spiritual renunciation, anxiety.',
    careerMeaning: 'Cyber intelligence, medical forensics, unconventional healing, deep cryptography, quantum theory.',
    wealthMeaning: 'Unpredictable financial cycles; requires disciplined wealth locking and clean transparent accounting.',
    relationshipMeaning: 'Complex and enigmatic; needs an exceptionally understanding partner who respects unique personal rhythms.',
    spiritualMeaning: 'Balancing the dual nodes of the cosmic serpent; transmuting worldly illusions into awakening.',
    remedy: 'Worship Lord Shiva and Lord Ganesha; feed stray dogs; practice daily grounding meditation.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-5': {
    code: '7-5',
    mulank: 7,
    bhagyank: 5,
    planetaryPair: 'Ketu - Mercury',
    title: 'The Forensic Mind / Ketu-Budha (केतु-बुध अनुसंधान योग)',
    positiveMeaning: 'Incisive analytical intellect, razor-sharp error detection, data forensics mastery, rapid problem-solving.',
    negativeMeaning: 'Nervous tension, over-critical analysis of colleagues, mental exhaustion from non-stop calculation.',
    careerMeaning: 'Data forensics, specialized scientific coding, investigative journalism, tax auditing, proprietary research.',
    wealthMeaning: 'Solid, reliable wealth earned through technical consulting, analytical patents, and specialized advisory.',
    relationshipMeaning: 'Communicative yet values intellectual independence; thrives with an intelligent, witty partner.',
    spiritualMeaning: 'Using analytical intellect to deconstruct false dogmas and uncover pristine truth.',
    remedy: 'Keep a clean green plant in North zone; feed green grass to cows; chant OM BUDHAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-6': {
    code: '7-6',
    mulank: 7,
    bhagyank: 6,
    planetaryPair: 'Ketu - Venus',
    title: 'The Sacred Aesthetic / Ketu-Shukra (केतु-शुक्र दिव्य कला योग)',
    positiveMeaning: 'Sublime artistic discernment, sacred design genius, devotional love, aesthetic refinement, spiritual magnetism.',
    negativeMeaning: 'Emotional detachment in relationships, disillusionment with conventional materialism, vulnerability to isolation.',
    careerMeaning: 'Sacred arts, holistic wellness therapy, antique curation, bespoke interior architecture, classical music.',
    wealthMeaning: 'Comfortable prosperity generated through distinctive artistic commissions and unique aesthetic mastery.',
    relationshipMeaning: 'Deeply devoted at a soul level; requires mutual respect for sacred space and gentle emotional handling.',
    spiritualMeaning: 'Recognizing divine beauty in all creation and utilizing art as a direct path of devotional surrender.',
    remedy: 'Donate white clothing to underprivileged girls; worship Lord Ganesha; chant OM SHUKRAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-7': {
    code: '7-7',
    mulank: 7,
    bhagyank: 7,
    planetaryPair: 'Ketu - Ketu',
    title: 'The Deep Transcendence / Double Ketu (केतु-केतु कैवल्य योग)',
    positiveMeaning: 'Extreme intuitive insight, profound spiritual detachment, mastery of the unconscious, forensic penetration.',
    negativeMeaning: 'Severe social isolation, feeling alienated from the material world, difficulty with mundane commercial tasks.',
    careerMeaning: 'Spiritual monasticism, solitary scientific research, clinical psychoanalysis, occult philosophy, deep forensics.',
    wealthMeaning: 'Material indifference; money flows best through specialized advisory and institutional grants.',
    relationshipMeaning: 'Very private and solitary; needs a companion who understands the absolute necessity of quiet contemplation.',
    spiritualMeaning: 'Supreme state of inner stillness (Kaivalya) and dissolution of worldly ego.',
    remedy: 'Worship Lord Ganesha daily; feed stray dogs; practice regular silent dhyana; wear a silver chain or ring.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-8': {
    code: '7-8',
    mulank: 7,
    bhagyank: 8,
    planetaryPair: 'Ketu - Saturn',
    title: 'The Ascetic Disciplinarian / Ketu-Shani (केतु-शनि वैराग्य योग)',
    positiveMeaning: 'Monumental endurance, deep philosophical realism, unshakeable patience, ability to bear heavy karmic responsibilities.',
    negativeMeaning: 'Severe early life trials, chronic feeling of burden, delayed emotional rewards, joint/bone stiffness.',
    careerMeaning: 'Archaeology, institutional history, geological research, palliative care administration, deep mining analytics.',
    wealthMeaning: 'Slow, steady accumulation of land and tangible long-term assets; builds unshakeable resilience.',
    relationshipMeaning: 'Extremely serious, loyal, and steadfast; takes years to build intimacy but remains permanent.',
    spiritualMeaning: 'Expiation of heavy ancestral karma through quiet duty, patience, and ascetic self-discipline.',
    remedy: 'Serve poor and elderly people on Saturdays; light mustard oil lamp under Peepal tree; chant OM SHIVAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '7-9': {
    code: '7-9',
    mulank: 7,
    bhagyank: 9,
    planetaryPair: 'Ketu - Mars',
    title: 'The Spiritual Warrior / Ketu-Mangal (केतु-मंगल पराक्रम योग)',
    positiveMeaning: 'Courageous defense of spiritual values, fearless conviction, penetrating strategic insight, humanitarian bravery.',
    negativeMeaning: 'Sudden temper flare-ups, intolerance for hypocrisy, impatience with slow compromise, accident vulnerability.',
    careerMeaning: 'Specialized surgery, defense intelligence, human rights investigation, emergency rescue operations, martial arts.',
    wealthMeaning: 'Solid wealth generated through swift, decisive actions and specialized technical mastery.',
    relationshipMeaning: 'Honest, fiercely loyal, and protective; requires a partner who values straightforward courage.',
    spiritualMeaning: 'Spiritual warfare against inner demons of ignorance, fear, and pride.',
    remedy: 'Recite Hanuman Chalisa; donate blood safely; support injured animals or veterans; chant OM KETAVE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 8-SERIES (Saturn Mulank)
  '8-1': {
    code: '8-1',
    mulank: 8,
    bhagyank: 1,
    planetaryPair: 'Saturn - Sun',
    title: 'The Hard-Won Sovereign / Shani-Surya (शनि-सूर्य संघर्ष योग)',
    positiveMeaning: 'Unmatched endurance, iron discipline, executive competence forged through trials, eventual massive societal authority.',
    negativeMeaning: 'Severe struggle in early career, conflict with superiors or paternal figures, feeling constantly tested.',
    careerMeaning: 'Corporate restructuring, heavy industrial governance, judiciary, civil administration, large-scale construction.',
    wealthMeaning: 'Solid, compounded permanent wealth built after initial delays; low risk of financial ruin.',
    relationshipMeaning: 'Responsible and dedicated; must consciously practice emotional warmth to avoid appearing cold.',
    spiritualMeaning: 'Karmic reconciliation between duty (Saturn) and soul sovereignty (Sun); forging character in fire.',
    remedy: 'Serve elderly workers; offer water to rising sun; maintain rigorous humility; avoid prideful arguments.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-2': {
    code: '8-2',
    mulank: 8,
    bhagyank: 2,
    planetaryPair: 'Saturn - Moon',
    title: 'The Emotional Stoic / Shani-Chandra (शनि-चन्द्र विष योग / तपस्या)',
    positiveMeaning: 'Profound emotional resilience, ability to bear deep suffering with grace, steadfast loyalty, grounded compassion.',
    negativeMeaning: 'Chronic melancholy, overthinking, feeling emotionally isolated or unappreciated, slow mood recovery.',
    careerMeaning: 'Public welfare administration, long-term healthcare, institutional counseling, civil rehabilitation, hospice care.',
    wealthMeaning: 'Steady, conservative wealth accumulation; thrives when investments are locked into secure land and physical assets.',
    relationshipMeaning: 'Extremely loyal and dependable; needs a partner who brings warmth, optimism, and emotional reassurance.',
    spiritualMeaning: 'Purification of the emotional mind through patience, forbearance, and compassionate service.',
    remedy: 'Drink water from silver glass; chant OM NAMAH SHIVAYA; avoid dark clothes on Mondays; honor mother and elders.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-3': {
    code: '8-3',
    mulank: 8,
    bhagyank: 3,
    planetaryPair: 'Saturn - Jupiter',
    title: 'The Judicial Anchor / Shani-Guru (शनि-गुरु धर्म-न्याय योग)',
    positiveMeaning: 'Impeccable ethical integrity, judicial wisdom, disciplined scholarship, steadfast patience, and executive respect.',
    negativeMeaning: 'Strict rigidity, tendency to impose high moral demands on others, delayed material expansion.',
    careerMeaning: 'Higher judiciary, constitutional law, institutional leadership, corporate compliance, civil engineering, history.',
    wealthMeaning: 'Substantial, enduring wealth accumulated over decades of structured service; protected from speculation.',
    relationshipMeaning: 'Noble, protective, and deeply responsible; values marital commitment and family honor above all.',
    spiritualMeaning: 'Mastery of Karma Yoga through righteous duty, institutional justice, and selfless service.',
    remedy: 'Help underprivileged students with study materials; light mustard oil lamp under Peepal tree on Saturdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-4': {
    code: '8-4',
    mulank: 8,
    bhagyank: 4,
    planetaryPair: 'Saturn - Rahu',
    title: 'The Iron Will Mastermind / Shani-Rahu (शनि-राहु वज्र योग)',
    positiveMeaning: 'Immense stamina, relentless perseverance, unshakeable resilience against hardships, technical mastery of heavy systems.',
    negativeMeaning: 'Severe early struggles, heavy delays, risk of legal complications or bone/joint strain, feeling burdened.',
    careerMeaning: 'Heavy engineering, mining, industrial manufacturing, corporate turnaround management, judicial administration.',
    wealthMeaning: 'Hard-earned permanent wealth; builds monumental physical assets after navigating rigorous early trials.',
    relationshipMeaning: 'Extremely serious, cautious, and steadfast; takes time to build emotional trust and intimacy.',
    spiritualMeaning: 'Deep karmic cleansing through enduring patience, selfless service, and humble labor.',
    remedy: 'Serve manual laborers on Saturdays; light mustard oil lamp under Peepal tree; feed black dogs; maintain rigorous integrity.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-5': {
    code: '8-5',
    mulank: 8,
    bhagyank: 5,
    planetaryPair: 'Saturn - Mercury',
    title: 'The Corporate Financier / Shani-Budha (शनि-बुध नीति योग)',
    positiveMeaning: 'Calculated business acumen, disciplined financial foresight, deep patience in market execution, enduring commercial systems.',
    negativeMeaning: 'Over-cautiousness causing missed opportunities, dry communication, mental fatigue under prolonged responsibility.',
    careerMeaning: 'Corporate auditing, institutional finance, industrial supply chains, real estate investments, tax consulting.',
    wealthMeaning: 'Highly stable, compounding wealth; builds massive tangible portfolios through methodical, risk-managed discipline.',
    relationshipMeaning: 'Dependable, steady, loyal, and practical; shows love through enduring support and financial security.',
    spiritualMeaning: 'Purifying commerce through ethical duty, fairness to workers, and disciplined stewardship.',
    remedy: 'Feed crows or black dogs on Saturdays; serve manual laborers; chant OM SHAM SHANAISCHARAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-6': {
    code: '8-6',
    mulank: 8,
    bhagyank: 6,
    planetaryPair: 'Saturn - Venus',
    title: 'The Material Architect / Shani-Shukra (शनि-शुक्र स्थायित्व योग)',
    positiveMeaning: 'Enduring material structures, pragmatic design mastery, deep patience in asset accumulation, loyalty in partnership.',
    negativeMeaning: 'Delayed romantic fulfillment, emotional seriousness, heavy domestic burdens, tendency toward melancholy.',
    careerMeaning: 'Real estate development, civil architecture, industrial design, luxury vintage trading, corporate law.',
    wealthMeaning: 'Permanent, compounded wealth; builds massive physical real estate and tangible assets over decades.',
    relationshipMeaning: 'Extremely loyal, protective, and steadfast; expresses love through reliable practical care and security.',
    spiritualMeaning: 'Harmonizing sensual aesthetic beauty with karmic discipline and selfless duty.',
    remedy: 'Serve elderly women on Saturdays; light sesame or mustard oil lamp; wear clean blue or off-white garments.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-7': {
    code: '8-7',
    mulank: 8,
    bhagyank: 7,
    planetaryPair: 'Saturn - Ketu',
    title: 'The Ascetic Disciplinarian / Shani-Ketu (शनि-केतु तपस्या योग)',
    positiveMeaning: 'Monumental endurance, deep philosophical realism, unshakeable patience, ability to bear heavy karmic responsibilities.',
    negativeMeaning: 'Severe early life trials, chronic feeling of burden, delayed emotional rewards, joint/bone stiffness.',
    careerMeaning: 'Archaeology, institutional history, geological research, palliative care administration, deep mining analytics.',
    wealthMeaning: 'Slow, steady accumulation of land and tangible long-term assets; builds unshakeable resilience.',
    relationshipMeaning: 'Extremely serious, loyal, and steadfast; takes years to build intimacy but remains permanent.',
    spiritualMeaning: 'Expiation of heavy ancestral karma through quiet duty, patience, and ascetic self-discipline.',
    remedy: 'Serve poor and elderly people on Saturdays; light mustard oil lamp under Peepal tree; chant OM SHIVAYA NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-8': {
    code: '8-8',
    mulank: 8,
    bhagyank: 8,
    planetaryPair: 'Saturn - Saturn',
    title: 'The Double Saturn Monolith / Double Shani (शनि-शनि कर्म योग)',
    positiveMeaning: 'Unsurpassed endurance, ironclad discipline, supreme realism, ability to manage massive industrial complexity.',
    negativeMeaning: 'Extreme delays, heavy life struggles, rigid worldview, chronic pessimism or fatigue, joint stiffness.',
    careerMeaning: 'Heavy infrastructure, mining, judicial governance, public works, institutional administration, metallurgy.',
    wealthMeaning: 'Immense permanent wealth accumulated through decades of unyielding labor; impervious to speculation.',
    relationshipMeaning: 'Solemn, dutiful, and deeply faithful; requires an optimistic, warm partner who brings light and levity.',
    spiritualMeaning: 'Total purification through selfless labor (Nishkama Karma); burning away all worldly illusions.',
    remedy: 'Serve disabled or poor workers on Saturdays; light mustard oil lamp; chant Hanuman Chalisa; practice flexibility.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '8-9': {
    code: '8-9',
    mulank: 8,
    bhagyank: 9,
    planetaryPair: 'Saturn - Mars',
    title: 'Steel and Fire / Shani-Mangal (शनि-मंगल द्वंद्व योग)',
    positiveMeaning: 'Formidable resilience, courageous perseverance under intense pressure, technical mastery, crisis leadership.',
    negativeMeaning: 'Internal tension between patience and fiery impulse, quick temper, risk of physical fatigue or joint strain.',
    careerMeaning: 'Defense engineering, heavy civil construction, emergency infrastructure, surgery, mining operations.',
    wealthMeaning: 'Strong wealth creation through property development, industrial machinery, and pioneering operations.',
    relationshipMeaning: 'Intense and dedicated; needs clear emotional communication to prevent simmering frustration.',
    spiritualMeaning: 'Forging spiritual steel in the furnace of trials; standing fearless in the face of adversity.',
    remedy: 'Recite Hanuman Chalisa on Tuesdays and Saturdays; serve laborers; donate blood safely; light mustard oil lamp.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },

  // 9-SERIES (Mars Mulank)
  '9-1': {
    code: '9-1',
    mulank: 9,
    bhagyank: 1,
    planetaryPair: 'Mars - Sun',
    title: 'The Sovereign Commander / Mangal-Surya (मंगल-सूर्य शौर्य योग)',
    positiveMeaning: 'Dynamic executive courage, fearless leadership, magnetic authority, passionate defense of righteous causes.',
    negativeMeaning: 'Explosive temper, stubborn pride, impatience with subordinate hesitation, vulnerability to burnout.',
    careerMeaning: 'Military command, high political office, emergency surgery, pioneering entrepreneurial founder, sports direction.',
    wealthMeaning: 'Rapid and aggressive wealth compounding through bold initiatives, prime real estate, and executive governance.',
    relationshipMeaning: 'Fiercely protective, loyal, and generous; requires a partner who radiates grounding calm.',
    spiritualMeaning: 'Aligning sovereign willpower with divine righteousness to protect the vulnerable.',
    remedy: 'Recite Hanuman Chalisa; offer water to the morning sun; practice cooling breathwork (Sheetali); donate red lentils.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-2': {
    code: '9-2',
    mulank: 9,
    bhagyank: 2,
    planetaryPair: 'Mars - Moon',
    title: 'The Protective Hero / Mangal-Chandra (मंगल-चन्द्र शक्ति योग)',
    positiveMeaning: 'Emotional courage, protective generosity, dynamic drive, intuitive entrepreneurial zest, humanitarian loyalty.',
    negativeMeaning: 'Emotional volatility, quick temper in domestic arguments, digestive heat, impulsive decisions under stress.',
    careerMeaning: 'Emergency medicine, sports psychology, social welfare advocacy, real estate brokerage, protective security.',
    wealthMeaning: 'Solid earning power through swift initiative, property acquisitions, and public goodwill.',
    relationshipMeaning: 'Passionate and fiercely protective of family; needs a calm, nurturing, and emotionally patient spouse.',
    spiritualMeaning: 'Transforming fiery passion into selfless protective service for family and society.',
    remedy: 'Drink water from a clay pot or silver vessel; avoid overly spicy food; chant Hanuman Chalisa; respect mother.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-3': {
    code: '9-3',
    mulank: 9,
    bhagyank: 3,
    planetaryPair: 'Mars - Jupiter',
    title: 'The Righteous Crusader / Mangal-Guru (मंगल-गुरु धर्म-शौर्य योग)',
    positiveMeaning: 'Noble valor, defense of ethical truth, inspiring academic or military mentorship, generous and brave leadership.',
    negativeMeaning: 'Dogmatic zeal, impatience with slow compromise, fiery arguments when core principles are debated.',
    careerMeaning: 'Military academy instruction, judicial enforcement, civil rights advocacy, sports coaching, higher surgery.',
    wealthMeaning: 'High earning capacity through courageous initiatives, land/property holdings, and prestigious leadership.',
    relationshipMeaning: 'Passionate, honorable, protective, and generous; values honesty and shared cultural ideals.',
    spiritualMeaning: 'Righteous crusade (Dharmayuddha); defending dharma and wisdom with unyielding courage.',
    remedy: 'Apply saffron or red sandalwood tilak; recite Hanuman Chalisa; donate to veterans or educational charities.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-4': {
    code: '9-4',
    mulank: 9,
    bhagyank: 4,
    planetaryPair: 'Mars - Rahu',
    title: 'The High-Voltage Dynamo / Mangal-Rahu (मंगल-राहु अंगारक योग)',
    positiveMeaning: 'Unstoppable physical vitality, fearless daring, technical innovation, ability to handle high-stakes crises.',
    negativeMeaning: 'Extreme temper, impulsiveness, proneness to sudden conflicts or accidents, friction with authorities.',
    careerMeaning: 'Defense intelligence, emergency rescue, advanced demolition, high-risk competitive athletics, crisis management.',
    wealthMeaning: 'Aggressive wealth capture through bold high-risk ventures; needs conservative wealth preservation.',
    relationshipMeaning: 'Intense and tempestuous; requires an exceptionally grounded partner who de-escalates tension.',
    spiritualMeaning: 'Transmuting raw aggression into disciplined spiritual valor and selfless protection of the weak.',
    remedy: 'Recite Hanuman Chalisa daily; avoid rash driving; donate blood safely; feed stray dogs on Saturdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-5': {
    code: '9-5',
    mulank: 9,
    bhagyank: 5,
    planetaryPair: 'Mars - Mercury',
    title: 'The Tactical Commander / Mangal-Budha (मंगल-बुध युक्ति योग)',
    positiveMeaning: 'Dynamic operational drive, sharp strategic instincts, rapid commercial execution, high problem-solving speed.',
    negativeMeaning: 'Sharp verbal bluntness, argumentative temper, impulsiveness in commercial negotiations, nervous strain.',
    careerMeaning: 'High-stakes sales leadership, technology startup scaling, military logistics, investigative reporting, property trading.',
    wealthMeaning: 'Rapid commercial wealth building; seizes lucrative opportunities swiftly through decisive initiatives.',
    relationshipMeaning: 'Passionate, energetic, and candid; seeks a partner who appreciates direct honesty and high enthusiasm.',
    spiritualMeaning: 'Using intellectual clarity and moral courage to champion noble causes and defeat ignorance.',
    remedy: 'Recite Hanuman Chalisa; donate green items on Wednesdays and red lentils on Tuesdays; practice peaceful speech.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-6': {
    code: '9-6',
    mulank: 9,
    bhagyank: 6,
    planetaryPair: 'Mars - Venus',
    title: 'The Passionate Catalyst / Mangal-Shukra (मंगल-शुक्र आकर्षण योग)',
    positiveMeaning: 'Intense charismatic magnetism, creative courage, passionate drive, generous humanitarian philanthropy.',
    negativeMeaning: 'Emotional volatility, heated arguments in intimate relationships, impulsive financial spending.',
    careerMeaning: 'Dramatic performing arts, luxury sports management, cosmetic surgery, real estate marketing, hospitality scaling.',
    wealthMeaning: 'Dynamic earning capacity; attracts substantial capital through bold creative and property investments.',
    relationshipMeaning: 'Fiercely passionate and protective; requires clear emotional boundaries and cooling domestic practices.',
    spiritualMeaning: 'Channeling intense vital passion into courageous humanitarian work and divine devotional service.',
    remedy: 'Drink water from clay vessels; practice cooling pranayama (Sheetali); recite Hanuman Chalisa on Tuesdays.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-7': {
    code: '9-7',
    mulank: 9,
    bhagyank: 7,
    planetaryPair: 'Mars - Ketu',
    title: 'The Spiritual Warrior / Mangal-Ketu (मंगल-केतु पराक्रम योग)',
    positiveMeaning: 'Courageous defense of spiritual values, fearless conviction, penetrating strategic insight, humanitarian bravery.',
    negativeMeaning: 'Sudden temper flare-ups, intolerance for hypocrisy, impatience with slow compromise, accident vulnerability.',
    careerMeaning: 'Specialized surgery, defense intelligence, human rights investigation, emergency rescue operations, martial arts.',
    wealthMeaning: 'Solid wealth generated through swift, decisive actions and specialized technical mastery.',
    relationshipMeaning: 'Honest, fiercely loyal, and protective; requires a partner who values straightforward courage.',
    spiritualMeaning: 'Spiritual warfare against inner demons of ignorance, fear, and pride.',
    remedy: 'Recite Hanuman Chalisa; donate blood safely; support injured animals or veterans; chant OM KETAVE NAMAH.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-8': {
    code: '9-8',
    mulank: 9,
    bhagyank: 8,
    planetaryPair: 'Mars - Saturn',
    title: 'Steel Under Pressure / Mangal-Shani (मंगल-शनि द्वंद्व योग)',
    positiveMeaning: 'Formidable resilience, courageous perseverance under intense pressure, technical mastery, crisis leadership.',
    negativeMeaning: 'Internal tension between patience and fiery impulse, quick temper, risk of physical fatigue or joint strain.',
    careerMeaning: 'Defense engineering, heavy civil construction, emergency infrastructure, surgery, mining operations.',
    wealthMeaning: 'Strong wealth creation through property development, industrial machinery, and pioneering operations.',
    relationshipMeaning: 'Intense and dedicated; needs clear emotional communication to prevent simmering frustration.',
    spiritualMeaning: 'Forging spiritual steel in the furnace of trials; standing fearless in the face of adversity.',
    remedy: 'Recite Hanuman Chalisa on Tuesdays and Saturdays; serve laborers; donate blood safely; light mustard oil lamp.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  },
  '9-9': {
    code: '9-9',
    mulank: 9,
    bhagyank: 9,
    planetaryPair: 'Mars - Mars',
    title: 'The Double Mars Firebrand / Double Mangal (मंगल-मंगल महा-शौर्य योग)',
    positiveMeaning: 'Boundless physical courage, explosive vitality, fearless pioneering drive, selfless humanitarian defense.',
    negativeMeaning: 'Severe hot temper, rash impulsiveness, risk of physical injury or burnout, confrontational tone.',
    careerMeaning: 'Special forces defense, trauma surgery, championship competitive sports, emergency disaster relief, pioneering exploration.',
    wealthMeaning: 'Rapid earnings through daring ventures and physical properties; requires conservative risk management.',
    relationshipMeaning: 'Intensely protective, honorable, and passionate; requires a partner who radiates cooling domestic serenity.',
    spiritualMeaning: 'Supreme Karma Yoga; sacrificing personal comfort to protect the weak and uphold righteousness.',
    remedy: 'Recite Hanuman Chalisa daily; practice Sheetali (cooling) pranayama; avoid hot spices; donate blood annually.',
    source: 'LeoFamily 81 Combinations Master Matrix / Raajeev Singh Chauhann Course'
  }
};
